@extends('layouts.mobile', [
    'heading' => 'Редактирование',
    'subheading' => collect([$donorCar->display_vin, $product->external_sku ?: $product->sku])->filter()->join(' · '),
])

@section('content')
    @php
        $photoUrl = fn (?string $path): ?string => \App\Support\PublicStorageUrl::url($path);
        $donorPartPresenter = app(\App\View\Admin\DonorCars\DonorPartDisplayPresenter::class);
        $catalogItem = $product->sourcePartCatalogItem;
        $productImages = $donorPartPresenter->productImages($product);
        $isTeslaDownloadedImage = fn (?string $path): bool => $donorPartPresenter->isTeslaDownloadedImage($path);
        $catalogSchemeImages = $donorPartPresenter->catalogSchemeImages($catalogItem);
        $catalogSchemePosition = $donorPartPresenter->catalogSchemePosition($catalogItem);
        $categoryPreviewUrl = $photoUrl($catalogItem?->category?->preview_image_url);
        $currentDamage = old('damage_note', array_key_exists((string) $product->notes, $damageOptions) ? (string) $product->notes : array_key_first($damageOptions));
        $checkedDamageStatuses = collect($checkedDamageStatuses ?? [])->map(fn ($value) => (string) $value)->values()->all();
        $currentStockItem = $product->stockItems
            ->filter(fn ($stockItem): bool => (int) $stockItem->quantity > 0)
            ->sortByDesc(fn ($stockItem): int => (int) $stockItem->available_quantity)
            ->first();
        $currentWarehouseId = old('warehouse_id', $currentStockItem?->warehouse_id);
        $currentFloor = old('floor', $currentStockItem?->location?->floor ?: 'floor_1');
        $currentLocationId = old('location_id', $currentStockItem?->location_id);
        $showPlacement = in_array((string) $currentDamage, $checkedDamageStatuses, true);
        $stockQuantity = (int) $product->stockItems->sum('quantity');
        $vehicleQuantity = null;

        if (preg_match('/Tesla VIN quantity:\s*(\d+)/u', (string) $product->description, $quantityMatches) === 1) {
            $vehicleQuantity = (int) $quantityMatches[1];
        } elseif ($product->isProtectedAutoGeneratedDonorProduct()) {
            $vehicleQuantity = 1;
        }

        $vehicleQuantityText = $vehicleQuantity !== null ? $vehicleQuantity.' '."\u{0448}\u{0442}" : null;
        $currentStockQuantity = old('stock_quantity', $showPlacement && $stockQuantity > 0 ? $stockQuantity : 1);
    @endphp

    <section class="mobile-actions">
        <a class="btn btn-secondary" href="{{ route('admin.mobile.donor-cars.parts.show', $donorCar) }}#part-{{ $product->id }}">Назад</a>
        <a class="btn btn-secondary" href="{{ route('admin.products.show', $product) }}">ПК</a>
    </section>

    <form method="POST" action="{{ route('admin.mobile.donor-cars.products.update', [$donorCar, $product]) }}" class="form-grid" data-mobile-edit-form>
        @csrf
        @method('PATCH')

        <section class="panel form-grid">
            @if($vehicleQuantityText !== null)
                <div class="donor-card__meta"><strong>{{ "\u{041A}\u{043E}\u{043B}-\u{0432}\u{043E} \u{043D}\u{0430} \u{043C}\u{0430}\u{0448}\u{0438}\u{043D}\u{0435}" }}:</strong> {{ $vehicleQuantityText }}</div>
            @endif

            <div class="mobile-quantity-stepper">
                <label for="part-stock-quantity">{{ "\u{041A}\u{043E}\u{043B}-\u{0432}\u{043E} \u{043D}\u{0430} \u{0441}\u{043A}\u{043B}\u{0430}\u{0434}\u{0435}" }}</label>
                <div class="mobile-quantity-stepper__controls">
                    <button type="button" class="btn btn-secondary" aria-label="{{ "\u{0423}\u{043C}\u{0435}\u{043D}\u{044C}\u{0448}\u{0438}\u{0442}\u{044C}" }}" data-quantity-step="-1">-</button>
                    <input id="part-stock-quantity" type="number" name="stock_quantity" value="{{ $currentStockQuantity }}" min="1" max="999" step="1" inputmode="numeric" data-quantity-input>
                    <button type="button" class="btn btn-secondary" aria-label="{{ "\u{0423}\u{0432}\u{0435}\u{043B}\u{0438}\u{0447}\u{0438}\u{0442}\u{044C}" }}" data-quantity-step="1">+</button>
                </div>
                @error('stock_quantity')<div class="error">{{ $message }}</div>@enderror
            </div>

            <div>
                <label for="part-name-ru">Название RU</label>
                <input id="part-name-ru" name="name_ru" value="{{ old('name_ru', $catalogItem?->name_ru ?: $product->name) }}" autocomplete="off">
                @error('name_ru')<div class="error">{{ $message }}</div>@enderror
            </div>

            <div>
                <label for="part-name-ua">Название УКР</label>
                <input id="part-name-ua" name="name_ua" value="{{ old('name_ua', $catalogItem?->name_ua) }}" autocomplete="off">
                @error('name_ua')<div class="error">{{ $message }}</div>@enderror
            </div>

            @unless($catalogItem)
                <div class="help">У этой запчасти нет связанной позиции каталога. RU/УКР название будет использовано как обычное название товара.</div>
            @endunless

            <div>
                <label for="part-external-sku">Артикул</label>
                <input id="part-external-sku" name="external_sku" value="{{ old('external_sku', $product->external_sku) }}" autocomplete="off">
                @error('external_sku')<div class="error">{{ $message }}</div>@enderror
            </div>

            <div>
                <label for="part-damage">Статус</label>
                <select id="part-damage" name="damage_note" required data-mobile-edit-damage-select>
                    @foreach($damageOptions as $damageValue => $damageLabel)
                        <option value="{{ $damageValue }}" @selected((string) $currentDamage === (string) $damageValue)>{{ $damageLabel }}</option>
                    @endforeach
                </select>
                @error('damage_note')<div class="error">{{ $message }}</div>@enderror
            </div>

            <div class="part-card__placement" data-mobile-edit-placement @unless($showPlacement) hidden @endunless>
                <div>
                    <label for="edit-warehouse-id">Склад</label>
                    <select id="edit-warehouse-id" name="warehouse_id" data-mobile-edit-warehouse-select data-selected-warehouse="{{ $currentWarehouseId }}" @disabled(! $showPlacement) @required($showPlacement)>
                        <option value="">Выберите склад</option>
                        @foreach(($placementWarehouseOptions ?? []) as $warehouseOption)
                            <option value="{{ $warehouseOption['id'] }}" @selected((string) $currentWarehouseId === (string) $warehouseOption['id'])>{{ $warehouseOption['name'] }}</option>
                        @endforeach
                    </select>
                    @error('warehouse_id')<div class="error">{{ $message }}</div>@enderror
                </div>

                <div data-mobile-edit-floor-wrap hidden>
                    <label for="edit-floor">Этаж</label>
                    <select id="edit-floor" name="floor" data-mobile-edit-floor-select data-selected-floor="{{ $currentFloor }}" disabled></select>
                    @error('floor')<div class="error">{{ $message }}</div>@enderror
                </div>

                <div data-mobile-edit-location-wrap hidden>
                    <label for="edit-location-search">Ячейка</label>
                    <div class="autocomplete" data-mobile-location-autocomplete>
                        <input id="edit-location-search" type="text" value="" autocomplete="off" inputmode="text" placeholder="Напр. A, A1, A/1" data-mobile-edit-location-search disabled>
                        <input id="edit-location-id" type="hidden" name="location_id" value="{{ $currentLocationId }}" data-mobile-edit-location-select data-selected-location="{{ $currentLocationId }}" disabled>
                        <div class="suggestions" data-mobile-edit-location-suggestions hidden></div>
                    </div>
                    @error('location_id')<div class="error">{{ $message }}</div>@enderror
                </div>
            </div>
        </section>

        <div class="sticky-actions">
            <button type="submit" class="btn-block">Сохранить</button>
        </div>
    </form>

    <section class="panel form-grid">
        <div class="donor-card__top">
            <div>
                <div class="donor-card__vin">Фото</div>
                <div class="donor-card__meta">{{ $productImages->count() }} шт.</div>
            </div>
            <form method="POST" action="{{ route('admin.mobile.donor-cars.products.photos.store', [$donorCar, $product]) }}" enctype="multipart/form-data" class="photo-actions" data-mobile-edit-photo-form>
                @csrf
                <input type="hidden" name="return_to" value="edit">
                <input id="edit-part-camera-photo" type="file" accept="image/*" capture="environment" hidden data-mobile-edit-photo-input data-mobile-edit-photo-name="photo">
                <input id="edit-part-gallery-photo" type="file" accept="image/*" hidden data-mobile-edit-photo-input data-mobile-edit-photo-name="photo">
                <label class="btn" for="edit-part-camera-photo">Сделать фото</label>
                <label class="btn btn-secondary" for="edit-part-gallery-photo">Загрузить</label>
            </form>
        </div>

        @if($productImages->isNotEmpty())
            @if($productImages->count() > 1)
                <form method="POST" action="{{ route('admin.mobile.donor-cars.products.photos.order', [$donorCar, $product]) }}" hidden data-mobile-photo-order-form>
                    @csrf
                    @method('PATCH')
                </form>
            @endif

            <div class="mobile-photo-grid" data-mobile-photo-sortable>
                @foreach($productImages as $photo)
                    @if($photoUrl($photo))
                        <div class="mobile-photo-tile" data-mobile-photo-tile data-photo="{{ $photo }}">
                            <img src="{{ $photoUrl($photo) }}" alt="Фото {{ $product->name }}">
                            <button type="button" class="mobile-photo-open" data-mobile-photo-open aria-label="Открыть фото"></button>
                            @if($productImages->count() > 1)
                                <button type="button" class="mobile-photo-drag-handle" aria-label="Перетащить фото" data-mobile-photo-drag-handle>
                                    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                        <path d="M9 5h2v2H9V5Zm4 0h2v2h-2V5ZM9 9h2v2H9V9Zm4 0h2v2h-2V9Zm-4 4h2v2H9v-2Zm4 0h2v2h-2v-2Zm-4 4h2v2H9v-2Zm4 0h2v2h-2v-2Z" />
                                    </svg>
                                </button>
                            @endif
                            @if($isTeslaDownloadedImage($photo))
                                <span class="tag mobile-photo-source-tag">tesla.com</span>
                            @else
                                <form method="POST" action="{{ route('admin.mobile.donor-cars.products.photos.destroy', [$donorCar, $product]) }}" class="mobile-photo-delete-form" data-mobile-photo-delete-form>
                                    @csrf
                                    @method('DELETE')
                                    <input type="hidden" name="photo" value="{{ $photo }}">
                                    <button type="submit" class="mobile-photo-delete-button" aria-label="Удалить фото">
                                        <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                            <path d="M9 3h6l1 2h4v2H4V5h4l1-2Zm1 6h2v9h-2V9Zm4 0h2v9h-2V9ZM7 9h2v10h6V9h2v12H7V9Z" />
                                        </svg>
                                    </button>
                                </form>
                            @endif
                            @if($photo === $product->main_image)
                                <span class="tag">Главное</span>
                            @endif
                        </div>
                    @endif
                @endforeach
            </div>

            <div class="mobile-photo-viewer" data-mobile-photo-viewer role="dialog" aria-modal="true" aria-label="Фото" hidden>
                <div class="mobile-photo-viewer__bar">
                    <div class="mobile-photo-viewer__counter" data-mobile-photo-viewer-counter></div>
                    <button type="button" class="mobile-photo-viewer__close" data-mobile-photo-viewer-close aria-label="Закрыть фото">&times;</button>
                </div>
                <div class="mobile-photo-viewer__frame" data-mobile-photo-viewer-frame>
                    <button type="button" class="mobile-photo-viewer__nav mobile-photo-viewer__nav--prev" data-mobile-photo-viewer-prev aria-label="Предыдущее фото">&#8249;</button>
                    <img class="mobile-photo-viewer__image" data-mobile-photo-viewer-image alt="">
                    <button type="button" class="mobile-photo-viewer__nav mobile-photo-viewer__nav--next" data-mobile-photo-viewer-next aria-label="Следующее фото">&#8250;</button>
                </div>
                <div class="mobile-photo-viewer__hint" data-mobile-photo-viewer-hint></div>
            </div>
        @else
            <div class="empty">Фото этой запчасти пока нет.</div>
        @endif
    </section>

    <section class="panel form-grid">
        <div>
            <div class="donor-card__vin">Схема узла</div>
            @if($catalogSchemePosition !== '')
                <div class="donor-card__meta">Позиция на схеме: {{ $catalogSchemePosition }}</div>
            @endif
        </div>

        @if($catalogSchemeImages->isNotEmpty())
            <div class="mobile-photo-grid mobile-photo-grid--scheme">
                @foreach($catalogSchemeImages as $schemeImage)
                    @if($photoUrl($schemeImage))
                        <div class="mobile-photo-tile mobile-photo-tile--scheme">
                            <img src="{{ $photoUrl($schemeImage) }}" alt="Схема {{ $product->external_sku ?: $product->sku }}">
                        </div>
                    @endif
                @endforeach
            </div>
        @else
            <div class="empty">Схема узла не найдена.</div>
        @endif
    </section>

    <script>
        (() => {
            const checkedDamageStatuses = new Set(@json($checkedDamageStatuses));
            const placementWarehouses = @json($placementWarehouseOptions ?? []);
            const placementLocations = @json($placementLocationOptions ?? []);
            const editDamageSelect = document.querySelector('[data-mobile-edit-damage-select]');
            const editPlacement = document.querySelector('[data-mobile-edit-placement]');
            const editWarehouseSelect = document.querySelector('[data-mobile-edit-warehouse-select]');
            const editFloorWrap = document.querySelector('[data-mobile-edit-floor-wrap]');
            const editFloorSelect = document.querySelector('[data-mobile-edit-floor-select]');
            const editLocationWrap = document.querySelector('[data-mobile-edit-location-wrap]');
            const editLocationSelect = document.querySelector('[data-mobile-edit-location-select]');
            const editLocationSearch = document.querySelector('[data-mobile-edit-location-search]');
            const editLocationSuggestions = document.querySelector('[data-mobile-edit-location-suggestions]');
            const rememberedWarehouseKey = 'mobile-donor-parts:last-placement-warehouse-id';
            const rememberedWarehouseCookieKey = 'mobile_donor_parts_last_placement_warehouse_id';
            const rememberedLocationKey = 'mobile-donor-parts:last-placement-location-id';
            const rememberedLocationCookieKey = 'mobile_donor_parts_last_placement_location_id';
            const rememberedServerWarehouseId = @json((string) ($rememberedPlacementWarehouseId ?? ''));
            const rememberedServerLocationId = @json((string) ($rememberedPlacementLocationId ?? ''));
            let currentCellLocations = [];

            document.querySelectorAll('[data-quantity-step]').forEach((button) => {
                button.addEventListener('click', () => {
                    const input = button.closest('.mobile-quantity-stepper')?.querySelector('[data-quantity-input]');
                    if (! input) return;

                    const step = Number(button.dataset.quantityStep || 0);
                    const min = Number(input.min || 1);
                    const max = Number(input.max || 999);
                    const current = Number.parseInt(input.value || String(min), 10);
                    input.value = String(Math.min(max, Math.max(min, (Number.isFinite(current) ? current : min) + step)));
                    input.dispatchEvent(new Event('input', { bubbles: true }));
                    input.dispatchEvent(new Event('change', { bubbles: true }));
                });
            });

            const fillSelect = (select, placeholder, options, selectedValue = '') => {
                if (! select) {
                    return;
                }

                const currentValue = String(select.value || selectedValue || '');
                select.innerHTML = '';
                select.append(new Option(placeholder, ''));

                options.forEach((option) => {
                    select.append(new Option(option.label, option.value ?? option.id ?? ''));
                });

                if (options.some((option) => String(option.value ?? option.id ?? '') === currentValue)) {
                    select.value = currentValue;
                }
            };
            const floorsFromLocations = (locations) => {
                const floors = new Map();

                locations.forEach((location) => {
                    if (location.floor && ! floors.has(location.floor)) {
                        floors.set(location.floor, location.floor_label || location.floor);
                    }
                });

                return Array.from(floors, ([value, label]) => ({ value, label }));
            };
            const normalizeLocationQuery = (value) => String(value || '')
                .toLocaleUpperCase('ru-RU')
                .replace(/[^0-9A-ZА-ЯЁІЇЄҐ]/g, '');
            const locationSearchText = (location) => normalizeLocationQuery(location.label);
            const hasPlacementWarehouse = (warehouseId) => placementWarehouses.some((item) => String(item.id) === String(warehouseId || ''));
            const selectedLocation = () => currentCellLocations.find((location) => String(location.id) === String(editLocationSelect?.value || ''));
            const cookieValue = (key) => {
                const match = document.cookie.match(new RegExp(`(?:^|; )${key}=([^;]*)`));

                return match ? window.decodeURIComponent(match[1]) : '';
            };
            const storeBrowserValue = (storageKey, cookieKey, value) => {
                if (! value) {
                    return;
                }

                try {
                    window.localStorage.setItem(storageKey, String(value));
                } catch (error) {
                    // localStorage can be unavailable in private or locked-down WebViews.
                }

                document.cookie = `${cookieKey}=${window.encodeURIComponent(String(value))}; max-age=31536000; path=/; samesite=lax`;
            };
            const storedBrowserValue = (storageKey, cookieKey) => {
                try {
                    const storedValue = window.localStorage.getItem(storageKey) || '';

                    if (storedValue) {
                        return storedValue;
                    }
                } catch (error) {
                    // localStorage can be unavailable in private or locked-down WebViews.
                }

                return cookieValue(cookieKey);
            };
            const rememberedWarehouseCookie = () => {
                return cookieValue(rememberedWarehouseCookieKey);
            };
            const rememberedWarehouseId = () => {
                return storedBrowserValue(rememberedWarehouseKey, rememberedWarehouseCookieKey) || rememberedWarehouseCookie();
            };
            const rememberWarehouseId = (warehouseId) => {
                storeBrowserValue(rememberedWarehouseKey, rememberedWarehouseCookieKey, warehouseId);
            };
            const rememberedLocationId = () => {
                return String(rememberedServerLocationId || storedBrowserValue(rememberedLocationKey, rememberedLocationCookieKey) || '');
            };
            const rememberLocationId = (locationId) => {
                storeBrowserValue(rememberedLocationKey, rememberedLocationCookieKey, locationId);
            };
            const setLocationSuggestionState = (isOpen) => {
                if (editLocationSuggestions) {
                    editLocationSuggestions.hidden = ! isOpen;
                }
            };
            const clearLocationSuggestions = () => {
                editLocationSuggestions?.replaceChildren();
                setLocationSuggestionState(false);
            };
            const selectEditLocation = (location, closeSuggestions = true) => {
                if (! location || ! editLocationSelect || ! editLocationSearch) {
                    return;
                }

                editLocationSelect.value = String(location.id);
                editLocationSelect.dataset.selectedLocation = String(location.id);
                editFloorSelect.value = location.floor || 'floor_1';
                editFloorSelect.dataset.selectedFloor = editFloorSelect.value;
                editLocationSearch.value = location.label || '';
                editLocationSearch.setCustomValidity('');
                rememberWarehouseId(editWarehouseSelect?.value || '');
                rememberLocationId(location.id);

                if (closeSuggestions) {
                    clearLocationSuggestions();
                }
            };
            const renderLocationSuggestions = () => {
                if (! editLocationSearch || ! editLocationSelect || ! editLocationSuggestions || editLocationSearch.disabled) {
                    clearLocationSuggestions();
                    return;
                }

                const query = normalizeLocationQuery(editLocationSearch.value);
                const lastLocationId = rememberedLocationId();
                const matches = currentCellLocations
                    .filter((location) => query === '' || locationSearchText(location).startsWith(query))
                    .sort((a, b) => {
                        const aIsLast = String(a.id) === lastLocationId;
                        const bIsLast = String(b.id) === lastLocationId;

                        if (aIsLast !== bIsLast) {
                            return aIsLast ? -1 : 1;
                        }

                        return String(a.label || '').localeCompare(String(b.label || ''), 'ru', { numeric: true, sensitivity: 'base' });
                    })
                    .slice(0, 30);

                editLocationSuggestions.replaceChildren();

                if (matches.length === 0) {
                    const empty = document.createElement('div');
                    empty.className = 'suggestion-empty';
                    empty.textContent = 'Нет ячеек по этому вводу';
                    editLocationSuggestions.append(empty);
                    setLocationSuggestionState(true);
                    return;
                }

                matches.forEach((location) => {
                    const button = document.createElement('button');
                    button.type = 'button';
                    button.className = 'suggestion';

                    const title = document.createElement('span');
                    title.className = 'suggestion__title';
                    title.textContent = location.label || '';

                    const meta = document.createElement('span');
                    meta.className = 'suggestion__meta';
                    meta.textContent = location.floor_label || '';

                    button.append(title, meta);
                    button.addEventListener('mousedown', (event) => event.preventDefault());
                    button.addEventListener('click', () => selectEditLocation(location));
                    editLocationSuggestions.append(button);
                });

                const exactMatches = matches.filter((location) => locationSearchText(location) === query);
                if (exactMatches.length === 1) {
                    editLocationSelect.value = String(exactMatches[0].id);
                    editLocationSelect.dataset.selectedLocation = editLocationSelect.value;
                    editFloorSelect.value = exactMatches[0].floor || 'floor_1';
                    editFloorSelect.dataset.selectedFloor = editFloorSelect.value;
                } else {
                    editLocationSelect.value = '';
                    editLocationSelect.dataset.selectedLocation = '';
                    editFloorSelect.dataset.selectedFloor = '';
                }
                editLocationSearch.setCustomValidity('');
                setLocationSuggestionState(true);
            };
            const setLocationSearchFromSelectedValue = () => {
                if (! editLocationSelect || ! editLocationSearch) {
                    return;
                }

                const location = selectedLocation()
                    || currentCellLocations.find((item) => String(item.id) === String(editLocationSelect.dataset.selectedLocation || ''));

                if (location) {
                    selectEditLocation(location, true);
                } else {
                    editLocationSelect.value = '';
                    editLocationSearch.value = '';
                    clearLocationSuggestions();
                }
            };
            const updateEditPlacement = () => {
                if (! editDamageSelect || ! editPlacement || ! editWarehouseSelect || ! editFloorWrap || ! editFloorSelect || ! editLocationWrap || ! editLocationSelect || ! editLocationSearch) {
                    return;
                }

                const shouldShow = checkedDamageStatuses.has(editDamageSelect.value);
                editPlacement.hidden = ! shouldShow;
                editWarehouseSelect.disabled = ! shouldShow;
                editWarehouseSelect.required = shouldShow;

                if (! shouldShow) {
                    editFloorWrap.hidden = true;
                    editFloorSelect.disabled = true;
                    editFloorSelect.required = false;
                    editLocationWrap.hidden = true;
                    editLocationSelect.disabled = true;
                    editLocationSearch.disabled = true;
                    editLocationSearch.required = false;
                    currentCellLocations = [];
                    clearLocationSuggestions();
                    return;
                }

                const selectedWarehouseId = String(editWarehouseSelect.value || '');
                const currentWarehouseId = String(editWarehouseSelect.dataset.selectedWarehouse || '');
                const serverWarehouseId = String(rememberedServerWarehouseId || '');
                const storedWarehouseId = String(rememberedWarehouseId() || '');
                const warehouseId = [selectedWarehouseId, currentWarehouseId, serverWarehouseId, storedWarehouseId]
                    .find((candidate) => candidate !== '' && hasPlacementWarehouse(candidate)) || '';

                if (warehouseId && ! editWarehouseSelect.value) {
                    editWarehouseSelect.value = warehouseId;
                }
                if (warehouseId) {
                    rememberWarehouseId(warehouseId);
                }

                const warehouse = placementWarehouses.find((item) => String(item.id) === warehouseId);
                const warehouseLocations = placementLocations.filter((location) => String(location.warehouse_id) === warehouseId);
                const floors = Array.isArray(warehouse?.floors) && warehouse.floors.length > 0
                    ? warehouse.floors
                    : floorsFromLocations(warehouseLocations);

                editFloorWrap.hidden = true;
                editFloorSelect.disabled = ! warehouseId;
                editFloorSelect.required = false;
                fillSelect(editFloorSelect, 'Выберите этаж', floors, editFloorSelect.dataset.selectedFloor || 'floor_1');

                if (floors.length === 1) {
                    editFloorSelect.value = floors[0].value;
                }

                const cellLocations = warehouseLocations
                    .filter((location) => location.has_cell);

                editLocationWrap.hidden = ! warehouseId || cellLocations.length === 0;
                editLocationSelect.disabled = editLocationWrap.hidden;
                editLocationSearch.disabled = editLocationWrap.hidden;
                editLocationSearch.required = ! editLocationWrap.hidden;
                currentCellLocations = cellLocations;
                setLocationSearchFromSelectedValue();
            };

            editDamageSelect?.addEventListener('change', updateEditPlacement);
            editWarehouseSelect?.addEventListener('change', () => {
                editWarehouseSelect.dataset.selectedWarehouse = '';
                rememberWarehouseId(editWarehouseSelect.value);
                editFloorSelect.dataset.selectedFloor = '';
                editLocationSelect.dataset.selectedLocation = '';
                editFloorSelect.value = '';
                editLocationSelect.value = '';
                if (editLocationSearch) {
                    editLocationSearch.value = '';
                }
                updateEditPlacement();
            });
            editFloorSelect?.addEventListener('change', () => {
                editFloorSelect.dataset.selectedFloor = '';
                editLocationSelect.dataset.selectedLocation = '';
                editLocationSelect.value = '';
                if (editLocationSearch) {
                    editLocationSearch.value = '';
                }
                updateEditPlacement();
            });
            editLocationSearch?.addEventListener('input', () => {
                editLocationSelect.value = '';
                editLocationSelect.dataset.selectedLocation = '';
                editFloorSelect.dataset.selectedFloor = '';
                renderLocationSuggestions();
            });
            editLocationSearch?.addEventListener('focus', renderLocationSuggestions);
            editLocationSearch?.addEventListener('blur', () => {
                window.setTimeout(() => setLocationSuggestionState(false), 120);
            });
            updateEditPlacement();

            const schemeFallbackSrc = @json($categoryPreviewUrl);
            const schemeGrid = document.querySelector('.mobile-photo-grid--scheme');
            const updateSchemeEmptyState = () => {
                if (! schemeGrid) {
                    return;
                }

                const visibleTiles = Array.from(schemeGrid.querySelectorAll('.mobile-photo-tile--scheme'))
                    .filter((tile) => ! tile.hidden);

                if (visibleTiles.length > 0 || schemeGrid.nextElementSibling?.hasAttribute('data-mobile-scheme-empty')) {
                    return;
                }

                const empty = document.createElement('div');
                empty.className = 'empty';
                empty.setAttribute('data-mobile-scheme-empty', '');
                empty.textContent = '\u0421\u0445\u0435\u043c\u0430 \u0443\u0437\u043b\u0430 \u043d\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u043b\u0430\u0441\u044c.';
                schemeGrid.after(empty);
            };
            const hideSchemeImage = (image) => {
                image.closest('.mobile-photo-tile--scheme')?.setAttribute('hidden', '');
                updateSchemeEmptyState();
            };
            const useSchemeFallback = (image) => {
                if (schemeFallbackSrc && image.src !== schemeFallbackSrc) {
                    image.src = schemeFallbackSrc;
                    return;
                }

                hideSchemeImage(image);
            };

            document.querySelectorAll('.mobile-photo-tile--scheme img').forEach((image) => {
                image.addEventListener('error', () => useSchemeFallback(image), { once: true });

                if (image.complete && image.naturalWidth === 0) {
                    useSchemeFallback(image);
                }
            });

            const editForm = document.querySelector('[data-mobile-edit-form]');
            const editStateFieldNames = ['name_ru', 'name_ua', 'external_sku', 'damage_note', 'stock_quantity', 'warehouse_id', 'floor', 'location_id'];
            editForm?.addEventListener('submit', (event) => {
                rememberWarehouseId(editWarehouseSelect?.value || '');

                if (! editLocationSearch || editLocationSearch.disabled || ! editLocationSearch.required || editLocationSelect.value) {
                    return;
                }

                const query = normalizeLocationQuery(editLocationSearch.value);
                const exactMatches = currentCellLocations.filter((location) => locationSearchText(location) === query);

                if (exactMatches.length === 1) {
                    selectEditLocation(exactMatches[0], true);
                    return;
                }

                editLocationSearch.setCustomValidity('Выберите ячейку из подсказок');
                editLocationSearch.reportValidity();
                event.preventDefault();
            });
            const syncPhotoFormEditState = (photoForm) => {
                if (! photoForm || ! editForm) {
                    return;
                }

                photoForm.querySelectorAll('[data-mobile-edit-state-field]').forEach((field) => field.remove());

                editStateFieldNames.forEach((name) => {
                    const field = editForm.querySelector(`[name="${name}"]`);

                    if (! field || field.disabled) {
                        return;
                    }

                    const input = document.createElement('input');
                    input.type = 'hidden';
                    input.name = name;
                    input.value = field.value;
                    input.setAttribute('data-mobile-edit-state-field', '');
                    photoForm.appendChild(input);
                });
            };

            document.querySelectorAll('[data-mobile-edit-photo-input]').forEach((input) => {
                input.addEventListener('change', () => {
                    if (input.files?.length > 0) {
                        input.form?.querySelectorAll('[data-mobile-edit-photo-input]').forEach((field) => {
                            if (field === input) {
                                field.setAttribute('name', field.dataset.mobileEditPhotoName || 'photo');
                            } else {
                                field.removeAttribute('name');
                                field.value = '';
                            }
                        });
                        syncPhotoFormEditState(input.form);
                        input.form?.submit();
                    }
                });
            });

            const viewer = document.querySelector('[data-mobile-photo-viewer]');
            if (viewer) {
                const viewerImage = viewer.querySelector('[data-mobile-photo-viewer-image]');
                const viewerFrame = viewer.querySelector('[data-mobile-photo-viewer-frame]');
                const viewerCounter = viewer.querySelector('[data-mobile-photo-viewer-counter]');
                const viewerHint = viewer.querySelector('[data-mobile-photo-viewer-hint]');
                const closeButton = viewer.querySelector('[data-mobile-photo-viewer-close]');
                const prevButton = viewer.querySelector('[data-mobile-photo-viewer-prev]');
                const nextButton = viewer.querySelector('[data-mobile-photo-viewer-next]');
                const photos = Array.from(document.querySelectorAll('[data-mobile-photo-open]'))
                    .map((button) => {
                        const image = button.closest('[data-mobile-photo-tile]')?.querySelector('img');

                        return {
                            button,
                            src: image?.currentSrc || image?.src || '',
                            alt: image?.alt || '',
                        };
                    })
                    .filter((photo) => photo.src !== '');
                const hasMultiplePhotos = photos.length > 1;
                let currentPhotoIndex = 0;
                let lastFocusedElement = null;
                let touchStartX = null;
                let touchStartY = null;

                const normalizePhotoIndex = (index) => {
                    if (photos.length === 0) {
                        return 0;
                    }

                    return (index + photos.length) % photos.length;
                };

                const showPhoto = (index) => {
                    if (photos.length === 0 || ! viewerImage) {
                        return;
                    }

                    currentPhotoIndex = normalizePhotoIndex(index);
                    const photo = photos[currentPhotoIndex];
                    viewerImage.src = photo.src;
                    viewerImage.alt = photo.alt;

                    if (viewerCounter) {
                        viewerCounter.textContent = hasMultiplePhotos ? `${currentPhotoIndex + 1} / ${photos.length}` : '';
                    }
                };

                const showRelativePhoto = (step) => {
                    if (! hasMultiplePhotos) {
                        return;
                    }

                    showPhoto(currentPhotoIndex + step);
                };

                const closeViewer = () => {
                    viewer.hidden = true;
                    document.body.classList.remove('is-mobile-photo-viewer-open');
                    viewerImage?.removeAttribute('src');

                    if (lastFocusedElement instanceof HTMLElement) {
                        lastFocusedElement.focus({ preventScroll: true });
                    }
                };

                const openViewer = (index) => {
                    if (photos.length === 0) {
                        return;
                    }

                    lastFocusedElement = document.activeElement;
                    showPhoto(index);
                    viewer.hidden = false;
                    document.body.classList.add('is-mobile-photo-viewer-open');
                    closeButton?.focus({ preventScroll: true });
                };

                [prevButton, nextButton, viewerCounter, viewerHint].forEach((element) => {
                    if (element) {
                        element.hidden = ! hasMultiplePhotos;
                    }
                });

                if (viewerHint && hasMultiplePhotos) {
                    viewerHint.textContent = '\u0421\u0432\u0430\u0439\u043f \u0432\u043b\u0435\u0432\u043e \u0438\u043b\u0438 \u0432\u043f\u0440\u0430\u0432\u043e';
                }

                photos.forEach((photo, index) => {
                    photo.button.addEventListener('click', () => openViewer(index));
                });

                closeButton?.addEventListener('click', closeViewer);
                prevButton?.addEventListener('click', () => showRelativePhoto(-1));
                nextButton?.addEventListener('click', () => showRelativePhoto(1));

                viewer.addEventListener('click', (event) => {
                    if (event.target === viewer || event.target === viewerFrame) {
                        closeViewer();
                    }
                });

                document.addEventListener('keydown', (event) => {
                    if (viewer.hidden) {
                        return;
                    }

                    if (event.key === 'Escape') {
                        closeViewer();
                    } else if (event.key === 'ArrowLeft') {
                        showRelativePhoto(-1);
                    } else if (event.key === 'ArrowRight') {
                        showRelativePhoto(1);
                    }
                });

                viewerFrame?.addEventListener('touchstart', (event) => {
                    if (event.touches.length !== 1) {
                        touchStartX = null;
                        touchStartY = null;
                        return;
                    }

                    touchStartX = event.touches[0].clientX;
                    touchStartY = event.touches[0].clientY;
                }, { passive: true });

                viewerFrame?.addEventListener('touchend', (event) => {
                    if (! hasMultiplePhotos || touchStartX === null || touchStartY === null || event.changedTouches.length !== 1) {
                        return;
                    }

                    const dx = event.changedTouches[0].clientX - touchStartX;
                    const dy = event.changedTouches[0].clientY - touchStartY;
                    touchStartX = null;
                    touchStartY = null;

                    if (Math.abs(dx) < 48 || Math.abs(dx) < Math.abs(dy) * 1.4) {
                        return;
                    }

                    showRelativePhoto(dx < 0 ? 1 : -1);
                }, { passive: true });
            }

            const sortable = document.querySelector('[data-mobile-photo-sortable]');
            const orderForm = document.querySelector('[data-mobile-photo-order-form]');
            const photoOrder = () => Array.from(sortable?.querySelectorAll('[data-mobile-photo-tile]') || [])
                .map((tile) => tile.dataset.photo || '')
                .filter(Boolean);
            const mainPhotoLabel = '\u0413\u043b\u0430\u0432\u043d\u043e\u0435';

            if (sortable && orderForm) {
                let draggedTile = null;
                let dragPreview = null;
                let dropTarget = null;
                let dragOffsetX = 0;
                let dragOffsetY = 0;
                let pendingDragPoint = null;
                let moveFrame = null;
                let startOrder = [];

                const clearDropTarget = () => {
                    dropTarget?.classList.remove('is-drop-target');
                    dropTarget = null;
                };

                const findDropTarget = (point) => {
                    const targetTile = document.elementFromPoint(point.clientX, point.clientY)?.closest('[data-mobile-photo-tile]');

                    if (targetTile && targetTile !== draggedTile && sortable.contains(targetTile)) {
                        return targetTile;
                    }

                    const sortableRect = sortable.getBoundingClientRect();
                    const edgeSlack = 42;
                    const isNearSortable = point.clientX >= sortableRect.left - edgeSlack
                        && point.clientX <= sortableRect.right + edgeSlack
                        && point.clientY >= sortableRect.top - edgeSlack
                        && point.clientY <= sortableRect.bottom + edgeSlack;

                    if (! isNearSortable) {
                        return null;
                    }

                    return Array.from(sortable.querySelectorAll('[data-mobile-photo-tile]'))
                        .filter((tile) => tile !== draggedTile)
                        .map((tile) => {
                            const rect = tile.getBoundingClientRect();
                            const centerX = rect.left + rect.width / 2;
                            const centerY = rect.top + rect.height / 2;

                            return {
                                tile,
                                distance: Math.hypot(point.clientX - centerX, point.clientY - centerY),
                            };
                        })
                        .sort((a, b) => a.distance - b.distance)[0]?.tile || null;
                };

                const moveDragPreview = (clientX, clientY) => {
                    if (! dragPreview) {
                        return;
                    }

                    const x = Math.round(clientX - dragOffsetX);
                    const y = Math.round(clientY - dragOffsetY);
                    dragPreview.style.transform = `translate3d(${x}px, ${y}px, 0) scale(1.04)`;
                };

                const removeDragPreview = () => {
                    dragPreview?.remove();
                    dragPreview = null;
                };

                const createDragPreview = (tile, event) => {
                    const rect = tile.getBoundingClientRect();
                    dragOffsetX = event.clientX - rect.left;
                    dragOffsetY = event.clientY - rect.top;
                    dragPreview = tile.cloneNode(true);
                    dragPreview.classList.remove('is-dragging', 'is-drop-target');
                    dragPreview.classList.add('mobile-photo-drag-preview');
                    dragPreview.setAttribute('aria-hidden', 'true');
                    dragPreview.removeAttribute('data-mobile-photo-tile');
                    dragPreview.removeAttribute('data-photo');
                    dragPreview.querySelectorAll('[data-mobile-photo-open], [data-mobile-photo-drag-handle], [data-mobile-photo-delete-form]').forEach((element) => element.remove());
                    dragPreview.style.width = `${rect.width}px`;
                    dragPreview.style.height = `${rect.height}px`;
                    document.body.appendChild(dragPreview);
                    moveDragPreview(event.clientX, event.clientY);
                };

                const updateMainPhotoBadge = () => {
                    sortable.querySelectorAll('.mobile-photo-tile > .tag:not(.mobile-photo-source-tag)').forEach((badge) => badge.remove());

                    const firstTile = sortable.querySelector('[data-mobile-photo-tile]');
                    if (! firstTile) {
                        return;
                    }

                    const badge = document.createElement('span');
                    badge.className = 'tag mobile-photo-main-tag';
                    badge.dataset.mobilePhotoMainBadge = '1';
                    badge.textContent = mainPhotoLabel;
                    firstTile.appendChild(badge);
                };

                const submitPhotoOrder = async (photos) => {
                    orderForm.querySelectorAll('[data-mobile-photo-order-input]').forEach((input) => input.remove());
                    photos.forEach((photo) => {
                        const input = document.createElement('input');
                        input.type = 'hidden';
                        input.name = 'photos[]';
                        input.value = photo;
                        input.dataset.mobilePhotoOrderInput = '1';
                        orderForm.appendChild(input);
                    });

                    try {
                        const response = await fetch(orderForm.action, {
                            method: orderForm.method || 'POST',
                            body: new FormData(orderForm),
                            credentials: 'same-origin',
                            headers: {
                                'Accept': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest',
                            },
                        });

                        if (! response.ok) {
                            throw new Error(`Photo order save failed: ${response.status}`);
                        }
                    } catch (error) {
                        window.location.reload();
                    }
                };

                const applyDragMove = (point) => {
                    if (! draggedTile) {
                        return;
                    }

                    moveDragPreview(point.clientX, point.clientY);
                    const targetTile = findDropTarget(point);
                    if (! targetTile) {
                        clearDropTarget();
                        return;
                    }

                    if (dropTarget !== targetTile) {
                        clearDropTarget();
                        dropTarget = targetTile;
                        dropTarget.classList.add('is-drop-target');
                    }

                };

                const applyDrop = (point) => {
                    const targetTile = findDropTarget(point);
                    if (! targetTile || ! draggedTile) {
                        return;
                    }

                    const tiles = Array.from(sortable.querySelectorAll('[data-mobile-photo-tile]'));
                    const draggedIndex = tiles.indexOf(draggedTile);
                    const targetIndex = tiles.indexOf(targetTile);

                    if (draggedIndex < 0 || targetIndex < 0 || draggedIndex === targetIndex) {
                        return;
                    }

                    sortable.insertBefore(draggedTile, draggedIndex < targetIndex ? targetTile.nextSibling : targetTile);
                };

                const queueDragMove = (event) => {
                    pendingDragPoint = {
                        clientX: event.clientX,
                        clientY: event.clientY,
                    };
                    if (moveFrame !== null) {
                        return;
                    }

                    moveFrame = window.requestAnimationFrame(() => {
                        const pointToApply = pendingDragPoint;
                        pendingDragPoint = null;
                        moveFrame = null;

                        if (pointToApply) {
                            applyDragMove(pointToApply);
                        }
                    });
                };

                const flushDragMove = () => {
                    if (moveFrame !== null) {
                        window.cancelAnimationFrame(moveFrame);
                        moveFrame = null;
                    }

                    const pointToApply = pendingDragPoint;
                    pendingDragPoint = null;

                    if (pointToApply) {
                        applyDragMove(pointToApply);
                    }
                };

                const finishDrag = (handle, event) => {
                    if (! draggedTile) {
                        return;
                    }

                    flushDragMove();
                    applyDrop({
                        clientX: event.clientX,
                        clientY: event.clientY,
                    });
                    draggedTile.classList.remove('is-dragging');
                    draggedTile.style.pointerEvents = '';
                    sortable.classList.remove('is-sorting');
                    clearDropTarget();
                    removeDragPreview();

                    if (handle?.hasPointerCapture?.(event.pointerId)) {
                        handle.releasePointerCapture(event.pointerId);
                    }

                    const nextOrder = photoOrder();
                    const hasChanged = startOrder.join('\n') !== nextOrder.join('\n');
                    draggedTile = null;
                    startOrder = [];

                    if (! hasChanged) {
                        return;
                    }

                    updateMainPhotoBadge();
                    submitPhotoOrder(nextOrder);
                };

                sortable.querySelectorAll('[data-mobile-photo-drag-handle]').forEach((handle) => {
                    handle.addEventListener('pointerdown', (event) => {
                        if (event.button && event.button !== 0) {
                            return;
                        }

                        draggedTile = handle.closest('[data-mobile-photo-tile]');
                        if (! draggedTile) {
                            return;
                        }

                        event.preventDefault();
                        startOrder = photoOrder();
                        draggedTile.classList.add('is-dragging');
                        draggedTile.style.pointerEvents = 'none';
                        sortable.classList.add('is-sorting');
                        createDragPreview(draggedTile, event);
                        handle.setPointerCapture?.(event.pointerId);
                    });

                    handle.addEventListener('pointermove', (event) => {
                        if (! draggedTile) {
                            return;
                        }

                        event.preventDefault();
                        queueDragMove(event);
                    });

                    handle.addEventListener('pointerup', (event) => finishDrag(handle, event));
                    handle.addEventListener('pointercancel', (event) => finishDrag(handle, event));
                });
            }

            document.querySelectorAll('[data-mobile-photo-delete-form]').forEach((form) => {
                form.addEventListener('submit', (event) => {
                    if (! window.confirm('\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u044d\u0442\u043e \u0444\u043e\u0442\u043e?')) {
                        event.preventDefault();
                    }
                });
            });
        })();
    </script>
@endsection
