<?php

namespace App\View\Admin\Product;

use App\Models\PartCatalogItem;
use App\Models\Product;
use App\Services\PartCatalogManualNameService;
use App\Support\PartCatalogRawAttributes;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class ProductShowPresenter
{
    public function __construct(
        protected PartCatalogManualNameService $catalogManualNameService,
    ) {}

    public function isNomenclatureProduct(Product $product): bool
    {
        $sourceItem = $product->sourcePartCatalogItem;

        if (! $sourceItem instanceof PartCatalogItem || $sourceItem->source !== 'nikolacars') {
            return false;
        }

        $sourceItemUrl = (string) ($sourceItem->source_url ?? '');
        $rawAttributes = PartCatalogRawAttributes::from($sourceItem);

        return Str::startsWith($sourceItemUrl, [
            'nikolacars://donor-product/',
            'nikolacars://inventory-product/',
        ]) || in_array((string) data_get($rawAttributes, 'source_type'), ['donor', 'warehouse', 'purchase'], true);
    }

    public function showAutoGeneratedBadge(Product $product): bool
    {
        return $product->is_auto_generated && ! $this->isNomenclatureProduct($product);
    }

    public function catalogNameManualLocks(Product $product): array
    {
        return $this->catalogNameManualLocksForItem($product->sourcePartCatalogItem);
    }

    public function catalogNameManualLocksForItem(?PartCatalogItem $sourceItem): array
    {
        if (! $sourceItem instanceof PartCatalogItem) {
            return [
                'ru' => false,
                'ua' => false,
            ];
        }

        $rawAttributes = PartCatalogRawAttributes::from($sourceItem);

        return [
            'ru' => (bool) (
                trim((string) $sourceItem->name_ru) !== ''
                && (
                    $this->catalogManualNameService->isLocked($sourceItem, 'name_ru')
                    || data_get($sourceItem, 'name_ru_manually_locked_at')
                    || data_get($rawAttributes, 'manual_name_locks.ru')
                )
            ),
            'ua' => (bool) (
                trim((string) $sourceItem->name_ua) !== ''
                && (
                    $this->catalogManualNameService->isLocked($sourceItem, 'name_ua')
                    || data_get($sourceItem, 'name_ua_manually_locked_at')
                    || data_get($rawAttributes, 'manual_name_locks.ua')
                )
            ),
        ];
    }

    public function catalogSourceUrl(Product $product): ?string
    {
        return $this->catalogSourceUrlForItem($product->sourcePartCatalogItem);
    }

    public function catalogSourceUrlForItem(?PartCatalogItem $sourceItem): ?string
    {
        if (! $sourceItem instanceof PartCatalogItem) {
            return null;
        }

        $rawAttributes = PartCatalogRawAttributes::from($sourceItem);

        return collect([
            data_get($rawAttributes, 'buy_url'),
            data_get($rawAttributes, 'product_url'),
            data_get($rawAttributes, 'teslashop_url'),
            data_get($rawAttributes, 'teslahelp_page_url'),
            $sourceItem->source_url,
        ])->first(fn (mixed $value): bool => is_string($value) && Str::startsWith($value, ['http://', 'https://']));
    }

    public function catalogSchemeImages(Product $product): Collection
    {
        return $this->catalogSchemeImagesForItem($product->sourcePartCatalogItem);
    }

    public function catalogSchemeImagesForItem(?PartCatalogItem $sourceItem): Collection
    {
        $rawAttributes = PartCatalogRawAttributes::from($sourceItem);
        $images = collect((array) data_get($rawAttributes, 'system_group_image_urls', []))
            ->filter(fn (mixed $value): bool => is_string($value) && trim($value) !== '')
            ->unique()
            ->values();

        if ($images->isEmpty() && $sourceItem?->category?->preview_image_url) {
            $images = collect([$sourceItem->category->preview_image_url]);
        }

        return $images->take(1)->values();
    }

    public function catalogSchemePosition(Product $product): string
    {
        return $this->catalogSchemePositionForItem($product->sourcePartCatalogItem);
    }

    public function catalogSchemePositionForItem(?PartCatalogItem $sourceItem): string
    {
        return trim((string) ($sourceItem?->scheme_number ?: data_get(PartCatalogRawAttributes::from($sourceItem), 'annotation')));
    }
}
