<?php

return [
    'sources' => [
        'tesla_official' => [
            'source' => 'tesla_official',
            'path' => 'tesla-official-catalog',
            'route_name' => 'tesla-official-catalog',
            'route_prefix' => 'admin.tesla-official-catalog',
            'permission' => 'tesla_catalog.view',
            'heading' => 'Каталог Tesla.com',
            'category_count_label' => 'Категорий Tesla.com',
            'source_label' => 'Tesla.com',
            'has_update_route' => true,
        ],
        'tcarservice' => [
            'source' => 'tcarservice',
            'path' => 'tcars-catalog',
            'route_name' => 'part-catalog',
            'route_prefix' => 'admin.part-catalog',
            'permission' => 'part_catalog.view',
            'heading' => 'Каталог TCARS',
            'category_count_label' => 'Категорий TCARS',
            'source_label' => 'Источник TCARS',
            'has_legacy_refresh_routes' => true,
            'has_update_route' => true,
        ],
        'teslapartsukraine' => [
            'source' => 'teslapartsukraine',
            'path' => 'teslapartsukraine-catalog',
            'route_name' => 'teslapartsukraine-catalog',
            'route_prefix' => 'admin.teslapartsukraine-catalog',
            'has_update_route' => true,
            'permission' => 'teslapartsukraine_catalog.view',
            'heading' => 'Каталог TeslaPartsUkraine',
            'category_count_label' => 'Категорий TeslaPartsUkraine',
            'source_label' => 'Источник TeslaPartsUkraine',
        ],
        'tsk' => [
            'source' => 'tsk',
            'path' => 'tsk-catalog',
            'route_name' => 'tsk-catalog',
            'route_prefix' => 'admin.tsk-catalog',
            'permission' => 'tsk_catalog.view',
            'heading' => 'Каталог TSK',
            'category_count_label' => 'Категорий TSK',
            'source_label' => 'Источник TSK',
            'has_update_route' => true,
        ],
        'stock-tesla' => [
            'source' => 'stock-tesla',
            'path' => 'stock-tesla-catalog',
            'route_name' => 'stock-tesla-catalog',
            'route_prefix' => 'admin.stock-tesla-catalog',
            'permission' => 'stock_tesla_catalog.view',
            'heading' => 'Catalog Stock Tesla',
            'category_count_label' => 'Categories Stock Tesla',
            'source_label' => 'Source Stock Tesla',
        ],
        'teslahelp' => [
            'source' => 'teslahelp',
            'path' => 'competitors-ru',
            'route_name' => 'competitors-ru',
            'route_prefix' => 'admin.competitors-ru',
            'permission' => 'competitors_ru.view',
            'heading' => '',
            'category_count_label' => ' ',
            'source_label' => 'Источник TeslaHelp',
        ],
        'driveparts' => [
            'source' => 'driveparts',
            'path' => 'driveparts-catalog',
            'route_name' => 'driveparts-catalog',
            'route_prefix' => 'admin.driveparts-catalog',
            'permission' => 'driveparts_catalog.view',
            'heading' => 'Каталог DriveParts',
            'category_count_label' => 'Категорий DriveParts',
            'source_label' => 'Источник DriveParts',
        ],
        'dkparts' => [
            'source' => 'dkparts',
            'path' => 'dkparts-catalog',
            'route_name' => 'dkparts-catalog',
            'route_prefix' => 'admin.dkparts-catalog',
            'permission' => 'dkparts_catalog.view',
            'heading' => 'Каталог DK-Parts',
            'category_count_label' => 'Категорий DK-Parts',
            'source_label' => 'Источник DK-Parts',
        ],
        'erazborka' => [
            'source' => 'erazborka',
            'path' => 'erazborka-catalog',
            'route_name' => 'erazborka-catalog',
            'route_prefix' => 'admin.erazborka-catalog',
            'permission' => 'erazborka_catalog.view',
            'heading' => 'Каталог Erazborka',
            'category_count_label' => 'Категорий Erazborka',
            'source_label' => 'Источник Erazborka',
        ],
        'toprazborka' => [
            'source' => 'toprazborka',
            'path' => 'toprazborka-catalog',
            'route_name' => 'toprazborka-catalog',
            'route_prefix' => 'admin.toprazborka-catalog',
            'permission' => 'toprazborka_catalog.view',
            'heading' => 'Каталог TopRazborka',
            'category_count_label' => 'Категорий TopRazborka',
            'source_label' => 'Источник TopRazborka',
        ],
        'teslawestparts' => [
            'source' => 'teslawestparts',
            'path' => 'teslawestparts-catalog',
            'route_name' => 'teslawestparts-catalog',
            'route_prefix' => 'admin.teslawestparts-catalog',
            'permission' => 'teslawestparts_catalog.view',
            'heading' => 'Каталог Tesla West Parts',
            'category_count_label' => 'Категорий Tesla West Parts',
            'source_label' => 'Источник Tesla West Parts',
        ],
        'teslacompany' => [
            'source' => 'teslacompany',
            'path' => 'teslacompany-catalog',
            'route_name' => 'teslacompany-catalog',
            'route_prefix' => 'admin.teslacompany-catalog',
            'permission' => 'teslacompany_catalog.view',
            'heading' => 'Каталог TeslaCompany',
            'category_count_label' => 'Категорий TeslaCompany',
            'source_label' => 'Источник TeslaCompany',
        ],
        'nikolacars' => [
            'source' => 'nikolacars',
            'path' => 'zapchasti',
            'route_name' => 'zapchasti',
            'route_prefix' => 'admin.zapchasti',
            'permission' => 'nikolacars_catalog.manage',
            'heading' => 'Запчасти НиколаКарз',
            'category_count_label' => 'Доноров / разделов НиколаКарз',
            'source_label' => 'Ссылка',
            'has_nikolacars_routes' => true,
        ],
    ],
];
