<?php

return [
    'permissions' => [
        'admin.users.manage' => [
            'label' => 'Управление доступами',
            'group' => 'Админ',
        ],
        'activity_logs.view' => [
            'label' => 'Журнал действий',
            'group' => 'Админ',
        ],
        'cashbook.manage' => [
            'label' => 'Касса и работы',
            'group' => 'СТО',
        ],
        'valera_cashbook.manage' => [
            'label' => 'Касса Валера',
            'group' => 'СТО',
        ],
        'sto_work_orders.manage' => [
            'label' => 'Заказ-наряды',
            'group' => 'СТО',
        ],
        'customer_orders.manage' => [
            'label' => 'Заказы',
            'group' => 'СТО',
        ],
        'sto_employees.manage' => [
            'label' => 'Сотрудники СТО',
            'group' => 'СТО',
        ],
        'donor_cars.manage' => [
            'label' => 'Доноры',
            'group' => 'Основное',
        ],
        'counterparties.manage' => [
            'label' => 'Контрагенты',
            'group' => 'Основное',
        ],
        'mobile_parts.manage' => [
            'label' => 'Мобильное добавление',
            'group' => 'Склад',
        ],
        'warehouses.manage' => [
            'label' => 'Склады',
            'group' => 'Склад',
        ],
        'locations.manage' => [
            'label' => 'Ячейки',
            'group' => 'Склад',
        ],
        'stock_items.manage' => [
            'label' => 'Остатки',
            'group' => 'Склад',
        ],
        'purchases.manage' => [
            'label' => 'Закупки',
            'group' => 'Склад',
        ],
        'movements.view' => [
            'label' => 'Движения',
            'group' => 'Склад',
        ],
        'reservations.manage' => [
            'label' => 'Резервы',
            'group' => 'Склад',
        ],
        'stock_actions.manage' => [
            'label' => 'Быстрые складские операции',
            'group' => 'Склад',
        ],
        'nikolacars_catalog.manage' => [
            'label' => 'Запчасти',
            'group' => 'Склад',
        ],
        'nikolacars_sales.view' => [
            'label' => 'Продажи NikolaCars',
            'group' => 'Склад',
        ],
        'categories.manage' => [
            'label' => 'Категории',
            'group' => 'Справочники',
        ],
        'brands.manage' => [
            'label' => 'Бренды',
            'group' => 'Справочники',
        ],
        'products.manage' => [
            'label' => 'Товары',
            'group' => 'Справочники',
        ],
        'tesla_catalog.view' => [
            'label' => 'Общий каталог Tesla',
            'group' => 'Справочники',
        ],
        'part_catalog.view' => [
            'label' => 'Каталог TCARS',
            'group' => 'Конкуренты',
        ],
        'teslapartsukraine_catalog.view' => [
            'label' => 'Каталог TeslaPartsUkraine',
            'group' => 'Конкуренты',
        ],
        'tsk_catalog.view' => [
            'label' => 'Каталог TSK',
            'group' => 'Конкуренты',
        ],
        'stock_tesla_catalog.view' => [
            'label' => 'Каталог Stock Tesla',
            'group' => 'Конкуренты',
        ],
        'competitors_ru.view' => [
            'label' => 'Конкуренты РУ',
            'group' => 'Конкуренты',
        ],
        'competitor_refresh.manage' => [
            'label' => 'Парсинг конкурентов',
            'group' => 'Конкуренты',
        ],
        'driveparts_catalog.view' => [
            'label' => 'Каталог DriveParts',
            'group' => 'Конкуренты',
        ],
        'dkparts_catalog.view' => [
            'label' => 'Каталог DK-Parts',
            'group' => 'Конкуренты',
        ],
        'erazborka_catalog.view' => [
            'label' => 'Каталог Erazborka',
            'group' => 'Конкуренты',
        ],
        'toprazborka_catalog.view' => [
            'label' => 'Каталог TopRazborka',
            'group' => 'Конкуренты',
        ],
        'teslawestparts_catalog.view' => [
            'label' => 'Каталог Tesla West Parts',
            'group' => 'Конкуренты',
        ],
        'teslacompany_catalog.view' => [
            'label' => 'Каталог TeslaCompany',
            'group' => 'Конкуренты',
        ],
        'exchange_rates.view' => [
            'label' => 'Курсы валют',
            'group' => 'Справочники',
        ],
        'reports.view' => [
            'label' => 'Отчеты',
            'group' => 'Отчеты',
        ],
    ],

    'roles' => [
        'admin' => [
            'label' => 'Админ',
            'permissions' => ['*'],
        ],
        'sto_manager' => [
            'label' => 'Руководитель СТО',
            'permissions' => [
                'cashbook.manage',
                'counterparties.manage',
                'donor_cars.manage',
                'stock_items.manage',
                'purchases.manage',
                'movements.view',
                'nikolacars_catalog.manage',
                'nikolacars_sales.view',
                'reports.view',
                'sto_employees.manage',
                'sto_work_orders.manage',
                'customer_orders.manage',
            ],
        ],
        'warehouse_worker' => [
            'label' => 'Работник склада',
            'permissions' => [
                'counterparties.manage',
                'donor_cars.manage',
                'mobile_parts.manage',
                'warehouses.manage',
                'locations.manage',
                'stock_items.manage',
                'purchases.manage',
                'movements.view',
                'reservations.manage',
                'stock_actions.manage',
                'nikolacars_catalog.manage',
                'nikolacars_sales.view',
                'categories.manage',
                'brands.manage',
                'products.manage',
                'tesla_catalog.view',
                'part_catalog.view',
                'teslapartsukraine_catalog.view',
                'tsk_catalog.view',
                'stock_tesla_catalog.view',
                'competitors_ru.view',
                'driveparts_catalog.view',
                'dkparts_catalog.view',
                'erazborka_catalog.view',
                'toprazborka_catalog.view',
                'teslawestparts_catalog.view',
                'teslacompany_catalog.view',
                'customer_orders.manage',
            ],
        ],
        'warehouse_limited' => [
            'label' => 'Работник склада без продаж',
            'permissions' => [
                'counterparties.manage',
                'donor_cars.manage',
                'mobile_parts.manage',
                'warehouses.manage',
                'locations.manage',
                'stock_items.manage',
                'purchases.manage',
                'movements.view',
                'reservations.manage',
                'stock_actions.manage',
                'categories.manage',
                'brands.manage',
                'products.manage',
                'tesla_catalog.view',
                'part_catalog.view',
                'teslapartsukraine_catalog.view',
                'tsk_catalog.view',
                'stock_tesla_catalog.view',
                'competitors_ru.view',
                'driveparts_catalog.view',
                'dkparts_catalog.view',
                'erazborka_catalog.view',
                'toprazborka_catalog.view',
                'teslawestparts_catalog.view',
                'teslacompany_catalog.view',
            ],
        ],

        // Legacy aliases kept so existing users with old seeded roles keep a sensible access level.
        'manager' => [
            'label' => 'Руководитель СТО',
            'permissions' => [
                'cashbook.manage',
                'reports.view',
                'sto_employees.manage',
                'sto_work_orders.manage',
                'customer_orders.manage',
            ],
        ],
        'storekeeper' => [
            'label' => 'Работник склада',
            'permissions' => [
                'counterparties.manage',
                'donor_cars.manage',
                'mobile_parts.manage',
                'warehouses.manage',
                'locations.manage',
                'stock_items.manage',
                'purchases.manage',
                'movements.view',
                'reservations.manage',
                'stock_actions.manage',
                'nikolacars_catalog.manage',
                'nikolacars_sales.view',
                'categories.manage',
                'brands.manage',
                'products.manage',
                'tesla_catalog.view',
                'part_catalog.view',
                'teslapartsukraine_catalog.view',
                'tsk_catalog.view',
                'stock_tesla_catalog.view',
                'competitors_ru.view',
                'driveparts_catalog.view',
                'dkparts_catalog.view',
                'erazborka_catalog.view',
                'toprazborka_catalog.view',
                'teslawestparts_catalog.view',
                'teslacompany_catalog.view',
                'customer_orders.manage',
            ],
        ],
        'picker' => [
            'label' => 'Работник склада',
            'permissions' => [
                'counterparties.manage',
                'donor_cars.manage',
                'mobile_parts.manage',
                'warehouses.manage',
                'locations.manage',
                'stock_items.manage',
                'purchases.manage',
                'movements.view',
                'reservations.manage',
                'stock_actions.manage',
                'nikolacars_catalog.manage',
                'nikolacars_sales.view',
                'categories.manage',
                'brands.manage',
                'products.manage',
                'tesla_catalog.view',
                'part_catalog.view',
                'teslapartsukraine_catalog.view',
                'tsk_catalog.view',
                'stock_tesla_catalog.view',
                'competitors_ru.view',
                'driveparts_catalog.view',
                'dkparts_catalog.view',
                'erazborka_catalog.view',
                'toprazborka_catalog.view',
                'teslawestparts_catalog.view',
                'teslacompany_catalog.view',
                'customer_orders.manage',
            ],
        ],
        'viewer' => [
            'label' => 'Просмотр',
            'permissions' => [],
        ],
    ],
];
