<?php

return [
    ['slug' => 'tesla-navigation-firmware', 'icon' => '🗺️', 'name_ru' => 'Прошивка навигации Tesla', 'name_uk' => 'Прошивка навігації Tesla'],
    ['slug' => 'tesla-drive-unit-oil-repair', 'icon' => '🛢️', 'name_ru' => 'Замена и ремонт масла в редукторе Tesla', 'name_uk' => 'Заміна та ремонт мастила в редукторі Tesla'],
    ['slug' => 'tesla-firmware-update', 'icon' => '💻', 'name_ru' => 'Обновление прошивки Tesla', 'name_uk' => 'Оновлення прошивки Tesla'],
    ['slug' => 'tesla-computer-diagnostics', 'icon' => '🧪', 'name_ru' => 'Компьютерная диагностика Tesla', 'name_uk' => 'Комп’ютерна діагностика Tesla'],
    ['slug' => 'tesla-pre-purchase-inspection', 'icon' => '🔍', 'name_ru' => 'Проверка Tesla перед покупкой', 'name_uk' => 'Перевірка Tesla перед купівлею'],
    ['slug' => 'tesla-tegra-intel-upgrade', 'icon' => '🧠', 'name_ru' => 'Tesla: замена и ремонт Tegra на Intel', 'name_uk' => 'Tesla: заміна та ремонт Tegra на Intel'],
    ['slug' => 'tesla-charge-port-repair', 'icon' => '🔌', 'name_ru' => 'Tesla: замена и ремонт порта зарядки', 'name_uk' => 'Tesla: заміна та ремонт порту заряджання'],
    ['slug' => 'tesla-brake-pads-repair', 'icon' => '🛑', 'name_ru' => 'Tesla: замена и ремонт колодок', 'name_uk' => 'Tesla: заміна та ремонт колодок'],
    ['slug' => 'tesla-mcu-repair', 'icon' => '📺', 'name_ru' => 'Tesla: замена и ремонт MCU', 'name_uk' => 'Tesla: заміна та ремонт MCU'],
    ['slug' => 'tesla-antifreeze-replacement', 'icon' => '🧊', 'name_ru' => 'Tesla: замена антифриза', 'name_uk' => 'Tesla: заміна антифризу'],
    ['slug' => 'tesla-cabin-filter-replacement', 'icon' => '🌬️', 'name_ru' => 'Tesla: замена салонного фильтра', 'name_uk' => 'Tesla: заміна салонного фільтра'],
    ['slug' => 'tesla-horn-repair', 'icon' => '📯', 'name_ru' => 'Замена и ремонт клаксона Tesla', 'name_uk' => 'Заміна та ремонт клаксона Tesla'],
    ['slug' => 'tesla-camera-repair', 'icon' => '📷', 'name_ru' => 'Замена и ремонт камеры Tesla', 'name_uk' => 'Заміна та ремонт камери Tesla'],
    ['slug' => 'tesla-console-display-repair', 'icon' => '🖥️', 'name_ru' => 'Замена и ремонт консоли и дисплея Tesla', 'name_uk' => 'Заміна та ремонт консолі й дисплея Tesla'],
    ['slug' => 'tesla-model-s-contactor-repair', 'icon' => '⚡', 'name_ru' => 'Замена и ремонт контакторов Tesla Model S', 'name_uk' => 'Заміна та ремонт контакторів Tesla Model S'],
    ['slug' => 'tesla-wiper-replacement', 'icon' => '🧽', 'name_ru' => 'Замена щеток Tesla', 'name_uk' => 'Заміна щіток Tesla'],
    ['slug' => 'tesla-heater-repair', 'icon' => '♨️', 'name_ru' => 'Замена и ремонт хитера Tesla', 'name_uk' => 'Заміна та ремонт хітера Tesla'],
    ['slug' => 'tesla-12v-battery-replacement', 'icon' => '🔋', 'name_ru' => 'Замена аккумулятора 12V Tesla', 'name_uk' => 'Заміна акумулятора 12V Tesla'],
    ['slug' => 'tesla-headlight-drl-repair', 'icon' => '💡', 'name_ru' => 'Замена и ремонт фары, лампы ближнего и ДХО Tesla', 'name_uk' => 'Заміна та ремонт фари, лампи ближнього та ДХВ Tesla'],
    ['slug' => 'tesla-pyrofuse-replacement', 'icon' => '🧨', 'name_ru' => 'Замена пиропатрона Tesla', 'name_uk' => 'Заміна піропатрона Tesla'],
    ['slug' => 'tesla-panoramic-roof-replacement', 'icon' => '🌤️', 'name_ru' => 'Замена панорамы Tesla', 'name_uk' => 'Заміна панорами Tesla'],
    ['slug' => 'tesla-processor-repair', 'icon' => '🧩', 'name_ru' => 'Замена и ремонт процессора Tesla', 'name_uk' => 'Заміна та ремонт процесора Tesla'],
    ['slug' => 'tesla-parking-sensor-repair', 'icon' => '📡', 'name_ru' => 'Замена и ремонт парктроника Tesla', 'name_uk' => 'Заміна та ремонт парктроніка Tesla'],
    ['slug' => 'tesla-model-s-battery-fuse', 'icon' => '🪫', 'name_ru' => 'Tesla Model S: замена предохранителя батареи', 'name_uk' => 'Tesla Model S: заміна запобіжника батареї'],
    ['slug' => 'tesla-radiator-repair', 'icon' => '🌡️', 'name_ru' => 'Замена и ремонт радиатора Tesla', 'name_uk' => 'Заміна та ремонт радіатора Tesla'],
    ['slug' => 'tesla-steering-rack-repair', 'icon' => '🛞', 'name_ru' => 'Замена и ремонт рейки руля Tesla', 'name_uk' => 'Заміна та ремонт рульової рейки Tesla'],
    ['slug' => 'tesla-control-arm-repair', 'icon' => '🔩', 'name_ru' => 'Замена и ремонт рычагов Tesla', 'name_uk' => 'Заміна та ремонт важелів Tesla'],
    ['slug' => 'tesla-windshield-repair', 'icon' => '🪟', 'name_ru' => 'Замена и ремонт лобового стекла Tesla', 'name_uk' => 'Заміна та ремонт лобового скла Tesla'],
    ['slug' => 'tesla-sim-card-repair', 'icon' => '📶', 'name_ru' => 'Замена и ремонт SIM-карты Tesla', 'name_uk' => 'Заміна та ремонт SIM-карти Tesla'],
    ['slug' => 'tesla-silentblock-repair', 'icon' => '🔧', 'name_ru' => 'Замена и ремонт сайлентблока Tesla', 'name_uk' => 'Заміна та ремонт сайлентблока Tesla'],
    ['slug' => 'tesla-hub-repair', 'icon' => '⚙️', 'name_ru' => 'Замена и ремонт ступицы Tesla', 'name_uk' => 'Заміна та ремонт ступиці Tesla'],
    ['slug' => 'tesla-inverter-repair', 'icon' => '🔁', 'name_ru' => 'Замена и ремонт инвертора Tesla', 'name_uk' => 'Заміна та ремонт інвертора Tesla'],
    ['slug' => 'tesla-air-strut-repair', 'icon' => '🫧', 'name_ru' => 'Замена и ремонт пневмостойки и пневмобаллона Tesla', 'name_uk' => 'Заміна та ремонт пневмостійки й пневмобалона Tesla'],
    ['slug' => 'tesla-suspension-repair', 'icon' => '🛠️', 'name_ru' => 'Ремонт подвески и пневмоподвески Tesla', 'name_uk' => 'Ремонт підвіски та пневмопідвіски Tesla'],
    ['slug' => 'tesla-window-regulator-repair', 'icon' => '⬆️', 'name_ru' => 'Ремонт стеклоподъемника Tesla', 'name_uk' => 'Ремонт склопідіймача Tesla'],
    ['slug' => 'tesla-control-unit-flash', 'icon' => '📟', 'name_ru' => 'Прошивка блоков Tesla', 'name_uk' => 'Прошивка блоків Tesla'],
    ['slug' => 'tesla-srs-crash', 'icon' => '🧯', 'name_ru' => 'Краш SRS Tesla', 'name_uk' => 'Краш SRS Tesla'],
    ['slug' => 'tesla-body-crash', 'icon' => '🚘', 'name_ru' => 'Краш BODY Tesla', 'name_uk' => 'Краш BODY Tesla'],
    ['slug' => 'tesla-battery-crash', 'icon' => '🔋', 'name_ru' => 'Краш АКБ Tesla', 'name_uk' => 'Краш АКБ Tesla'],
    ['slug' => 'tesla-air-suspension-crash', 'icon' => '🫧', 'name_ru' => 'Краш пневмо-подвески Tesla', 'name_uk' => 'Краш пневмо-підвіски Tesla'],
    ['slug' => 'tesla-modem-repair', 'icon' => '📡', 'name_ru' => 'Замена и ремонт модема Tesla', 'name_uk' => 'Заміна та ремонт модема Tesla'],
    ['slug' => 'tesla-radar-calibration', 'icon' => '📍', 'name_ru' => 'Калибровка радара Tesla', 'name_uk' => 'Калібрування радара Tesla'],
    ['slug' => 'tesla-camera-calibration', 'icon' => '🎯', 'name_ru' => 'Калибровка камеры Tesla', 'name_uk' => 'Калібрування камери Tesla'],
    ['slug' => 'tesla-key-flash', 'icon' => '🔑', 'name_ru' => 'Прошить ключ Tesla', 'name_uk' => 'Прошити ключ Tesla'],
    ['slug' => 'tesla-ccs-charge-port-repair', 'icon' => '🔌', 'name_ru' => 'Замена и ремонт порта зарядки Tesla на CCS', 'name_uk' => 'Заміна та ремонт порту заряджання Tesla на CCS'],
];
