@extends('layouts.admin', ['heading' => $productHeading ?? $product->name])

@php
    $productShowPresenter = app(\App\View\Admin\Product\ProductShowPresenter::class);
    $showAutoGeneratedBadge = $productShowPresenter->showAutoGeneratedBadge($product);
    $damageNote = trim((string) \App\Support\CatalogTextEncoding::repair($product->notes ?? ''));
    $isCheckedDonorProduct = $product->donorCar
        && in_array($damageNote, \App\Services\NikolaCarsProductInventorySyncService::CHECKED_DAMAGE_STATUSES, true);
    $isUncheckedDonorProduct = $product->donorCar
        && ! $isCheckedDonorProduct
        && $damageNote !== \App\Services\NikolaCarsProductInventorySyncService::BROKEN_DAMAGE_STATUS;
@endphp

@if($showAutoGeneratedBadge || $isCheckedDonorProduct || $isUncheckedDonorProduct)
    @section('heading-actions')
        @if($showAutoGeneratedBadge)
            <span class="auto-generated-badge" title="Автоматически сгенерировано из каталога запчастей." aria-label="Автоматически сгенерировано из каталога запчастей.">A</span>
        @endif
        @if($isCheckedDonorProduct)
            <span class="tag product-heading-status product-heading-status--checked">{{ $damageNote }}</span>
        @elseif($isUncheckedDonorProduct)
            <span class="tag tag-warning product-heading-status">Не проверен</span>
        @endif
    @endsection
@endif

@section('content')
    @php
        $imageUrl = fn (?string $path): ?string => \App\Support\PublicStorageUrl::url($path);
        $officialPartImages = collect((array) (($nikolaCarsOfficialEnrichment ?? null)?->partImageUrls ?? []))
            ->filter()
            ->unique(fn ($photo): string => \App\Support\ProductPhotoNormalizer::imageKey($photo))
            ->values();
        $officialSchemeImages = collect((array) (($nikolaCarsOfficialEnrichment ?? null)?->schemeImageUrls ?? []))
            ->filter()
            ->unique(fn ($photo): string => \App\Support\ProductPhotoNormalizer::imageKey($photo))
            ->values();

        $storedProductImages = \App\Support\ProductPhotoNormalizer::productPhotos($product, $officialPartImages);
        $storedProductImageKeys = $storedProductImages
            ->mapWithKeys(fn ($photo): array => [\App\Support\ProductPhotoNormalizer::imageKey($photo) => true]);
        $officialPartImagesForInline = $officialPartImages
            ->reject(fn ($photo): bool => $storedProductImageKeys->has(\App\Support\ProductPhotoNormalizer::imageKey($photo)))
            ->values();
        $officialSchemeImagesForInline = $officialSchemeImages;
        $productImages = $storedProductImages;
        $donorMainImage = collect($product->donorCar?->photos ?? [])->filter()->first();

        if ($donorMainImage) {
            $productImages = $productImages
                ->reject(fn ($photo): bool => $photo === $donorMainImage)
                ->when(
                    $product->storage_status === \App\Models\Product::STORAGE_STATUS_ON_DONOR,
                    fn ($images) => $images->push($donorMainImage)
                )
                ->values();
        }
        $isTeslaDownloadedImage = fn (?string $path): bool => str_contains((string) $path, 'tesla-official/part-images/');

        $sideLabels = [
            'left' => 'Левая',
            'right' => 'Правая',
            'front' => 'Передняя',
            'rear' => 'Задняя',
        ];
        $conditionTypeLabels = \App\Models\Product::CONDITION_TYPE_LABELS;
        $testingLabels = [
            'tested' => 'Проверен',
            'not_tested' => 'Не проверен',
        ];
        $unitLabels = [
            'pcs' => 'шт',
            'set' => 'комплект',
            'pair' => 'пара',
        ];
        $movementLabels = [
            'intake' => 'Приемка',
            'move' => 'Перемещение',
            'reserve' => '',
            'unreserve' => 'Снятие резерва',
            'sale' => 'Продажа',
            'writeoff' => 'Списание',
            'adjustment' => 'Корректировка',
        ];
        $nameWithAutoBadge = function (?string $value): array {
            $value = trim((string) $value);

            return [
                'text' => $value,
                'is_auto' => false,
            ];
        };
        $autoGeneratedTooltip = "\u{0410}\u{0432}\u{0442}\u{043E}\u{043C}\u{0430}\u{0442}\u{0438}\u{0447}\u{0435}\u{0441}\u{043A}\u{0438} \u{0441}\u{0433}\u{0435}\u{043D}\u{0435}\u{0440}\u{0438}\u{0440}\u{043E}\u{0432}\u{0430}\u{043D}\u{043E} \u{0438}\u{0437} \u{043A}\u{0430}\u{0442}\u{0430}\u{043B}\u{043E}\u{0433}\u{0430} \u{0437}\u{0430}\u{043F}\u{0447}\u{0430}\u{0441}\u{0442}\u{0435}\u{0439}.";
        $displayDescription = trim((string) $product->description);

        if ($product->is_auto_generated) {
            $hiddenAutoDescriptionLines = [
                $autoGeneratedTooltip,
                "\u{0418}\u{0441}\u{0442}\u{043E}\u{0447}\u{043D}\u{0438}\u{043A}:",
                "\u{0421}\u{0441}\u{044B}\u{043B}\u{043A}\u{0430}:",
            ];
            $displayDescription = collect(preg_split('/\R/u', $displayDescription) ?: [])
                ->reject(function (string $line) use ($hiddenAutoDescriptionLines): bool {
                    $line = trim($line);

                    return $line === $hiddenAutoDescriptionLines[0]
                        || \Illuminate\Support\Str::startsWith($line, [$hiddenAutoDescriptionLines[1], $hiddenAutoDescriptionLines[2]]);
                })
                ->implode(PHP_EOL);
        }
        $colorSwatchHex = function (?string $color): ?string {
            $normalized = mb_strtolower(trim((string) $color));

            if ($normalized === '') {
                return null;
            }

            return match (true) {
                preg_match('/\b(white|pearl)\b/u', $normalized) === 1 || str_contains($normalized, 'бел') || str_contains($normalized, 'білий') => '#f8fafc',
                preg_match('/\b(black|obsidian)\b/u', $normalized) === 1 || str_contains($normalized, 'черн') || str_contains($normalized, 'чорн') => '#111827',
                preg_match('/\b(red|ultra)\b/u', $normalized) === 1 || str_contains($normalized, 'красн') || str_contains($normalized, 'червон') => '#dc2626',
                preg_match('/\b(blue|navy)\b/u', $normalized) === 1 || str_contains($normalized, 'син') => '#2563eb',
                preg_match('/\b(grey|gray|silver|quicksilver|midnight)\b/u', $normalized) === 1 || str_contains($normalized, 'сер') || str_contains($normalized, 'сріб') => '#94a3b8',
                preg_match('/\b(green)\b/u', $normalized) === 1 || str_contains($normalized, 'зелен') => '#16a34a',
                preg_match('/\b(yellow|gold)\b/u', $normalized) === 1 || str_contains($normalized, 'желт') || str_contains($normalized, 'жовт') || str_contains($normalized, 'золот') => '#facc15',
                preg_match('/\b(brown|bronze)\b/u', $normalized) === 1 || str_contains($normalized, 'корич') || str_contains($normalized, 'бронз') => '#92400e',
                default => null,
            };
        };

        $stockQuantity = (int) $product->stockItems->sum('quantity');
        $vehicleQuantityText = null;

        if ($product->donorCar) {
            $vehicleQuantity = null;

            if (preg_match('/Tesla VIN quantity:\s*(\d+)/u', (string) $product->description, $quantityMatches) === 1) {
                $vehicleQuantity = (int) $quantityMatches[1];
            }

            $vehicleQuantity ??= max(1, $stockQuantity);
            $vehicleQuantityText = $vehicleQuantity.' '."\u{0448}\u{0442}";
        }

        $storageStatusLabel = $product->storage_status_label;

        if ($product->storage_status === \App\Models\Product::STORAGE_STATUS_IN_STOCK && $stockQuantity <= 0) {
            $storageStatusLabel = \App\Models\Product::STORAGE_STATUSES[\App\Models\Product::STORAGE_STATUS_SOLD];
        }
        $isSoldProduct = $product->storage_status === \App\Models\Product::STORAGE_STATUS_SOLD;
        $isTeslaOfficialProduct = $product->isTeslaOfficialGenerated();
        $primaryArticle = trim((string) ($product->external_sku ?: $product->sourcePartCatalogItem?->part_number));
        $nikolaCarsOfficialEnrichment = $nikolaCarsOfficialEnrichment ?? null;
        $catalogItem = $catalogItem ?? $product->sourcePartCatalogItem;
        $officialCatalogItem = $officialCatalogItem ?? ($nikolaCarsOfficialEnrichment?->officialItem ?? null);
        $catalogSchemeItem = $officialCatalogItem ?: $catalogItem;
        $donorSummaryLabel = $product->storage_status === \App\Models\Product::STORAGE_STATUS_ON_DONOR
            ? "\u{0420}\u{0430}\u{0441}\u{043F}\u{043E}\u{043B}\u{043E}\u{0436}\u{0435}\u{043D}\u{0438}\u{0435} \u{043D}\u{0430} \u{043D}\u{0430}\u{0448}\u{0435}\u{043C} \u{0441}\u{043A}\u{043B}\u{0430}\u{0434}\u{0435}"
            : "\u{0421}\u{043D}\u{044F}\u{0442}\u{043E} \u{0441} \u{0434}\u{043E}\u{043D}\u{043E}\u{0440}\u{0430}";
        $stockPlacementFloorLabel = function ($location): string {
            $floor = (string) ($location?->floor ?? '');

            if (preg_match('/^floor_(\d+)$/', $floor, $matches)) {
                return "\u{042D}\u{0442}\u{0430}\u{0436} {$matches[1]}";
            }

            return "\u{2014}";
        };
        $stockPlacementRows = $product->stockItems
            ->filter(fn ($stockItem): bool => (int) $stockItem->quantity > 0)
            ->map(fn ($stockItem): array => [
                'warehouse' => $stockItem->warehouse?->name ?: "\u{2014}",
                'is_donor_warehouse' => $stockItem->warehouse?->type === \App\Models\Warehouse::TYPE_DONOR,
                'floor' => $stockPlacementFloorLabel($stockItem->location),
                'cell' => $stockItem->location?->shortCode() ?: "\u{2014}",
                'quantity' => (int) $stockItem->quantity,
            ])
            ->values();

        $details = [
            'ID' => $product->id,
            'SKU' => $product->sku,
            'Артикул' => $product->external_sku,
            'Slug' => $product->slug,
            'Категория' => $product->category?->name,
            'Бренд' => $product->brand?->name,
            'Донор' => $product->donorCar?->vin,
            'Тип запчасти' => $product->part_origin_label,
            'Модель' => $product->model,
            'Цвет' => $product->color,
            'Поколение' => $product->generation,
            'Сторона' => $sideLabels[$product->side] ?? $product->side,
            'Тип состояния' => $conditionTypeLabels[$product->condition_type] ?? $product->condition_type,
            'Проверка' => $testingLabels[$product->testing_status] ?? $product->testing_status,
            'Статус хранения' => $storageStatusLabel,
            'Остаток' => $stockQuantity,
            'Единица' => $unitLabels[$product->unit] ?? $product->unit,
            'Закупочная цена' => $product->purchase_price !== null ? $product->purchase_price.' '.$product->currency : null,
            'Цена продажи' => $product->selling_price !== null ? $product->selling_price.' '.$product->currency : null,
            'Валюта' => $product->currency,
            'Штрихкод' => $product->barcode,
            'QR-код' => $product->qr_code,
            'Главное изображение' => $product->main_image,
            'Всего фото' => $storedProductImages->count(),
            'Вес' => $product->weight !== null ? $product->weight.' кг' : null,
            'Автосоздан' => $showAutoGeneratedBadge ? 'Да' : 'Нет',
            'ID источника каталога' => $product->source_part_catalog_item_id,
            'Источник каталога' => $catalogItem
                ? collect([$catalogItem->part_number, $catalogItem->name])->filter()->implode(' · ')
                : null,
            'Дата генерации' => optional($product->generated_at)->format('Y-m-d H:i'),
            'Активен' => $product->is_active ? 'Да' : 'Нет',
            'Создал пользователь ID' => $product->created_by,
            'Обновил пользователь ID' => $product->updated_by,
            'Создан' => optional($product->created_at)->format('Y-m-d H:i'),
            'Обновлен' => optional($product->updated_at)->format('Y-m-d H:i'),
        ];
        $catalogNameRu = $nameWithAutoBadge($catalogItem?->name_ru);
        $catalogNameUa = $nameWithAutoBadge($catalogItem?->name_ua);
        $catalogNameEn = trim((string) ($catalogItem?->name_en ?: $catalogItem?->name ?: ''));
        $catalogNameManualLocks = $productShowPresenter->catalogNameManualLocksForItem($catalogItem);
        $catalogNameRuManual = $catalogNameManualLocks['ru'];
        $catalogNameUaManual = $catalogNameManualLocks['ua'];
        $catalogNameSources = $catalogNameSources ?? [
            'ru' => ['site' => null, 'url' => null],
            'ua' => ['site' => null, 'url' => null],
        ];
        $catalogSourceUrl = $productShowPresenter->catalogSourceUrlForItem($catalogItem);
        $catalogSchemeImages = $productShowPresenter->catalogSchemeImagesForItem($catalogSchemeItem);
        $catalogSchemePosition = $productShowPresenter->catalogSchemePositionForItem($catalogSchemeItem);
        $nikolaCarsOfficialMatchLabels = [
            \App\Services\NikolaCarsOfficialPartMatch::TYPE_EXACT => 'Точное совпадение',
            \App\Services\NikolaCarsOfficialPartMatch::TYPE_SEVEN_DIGIT_PREFIX => 'По первым 7 цифрам',
            \App\Services\NikolaCarsOfficialPartMatch::TYPE_NONE => 'Не найдено',
        ];
        $nikolaCarsOfficialMatchLabel = $nikolaCarsOfficialEnrichment
            ? ($nikolaCarsOfficialMatchLabels[$nikolaCarsOfficialEnrichment->matchType()] ?? $nikolaCarsOfficialEnrichment->matchType())
            : null;
    @endphp

    <div class="product-show">
        <div class="panel product-item-main-panel">
            @unless($isSoldProduct)
                <a class="btn btn-secondary product-edit-button" href="{{ route('admin.products.edit', $product) }}">Изменить</a>
            @endunless

            <div class="product-item-layout">
                <div class="product-item-details">
                    <div class="help">Артикул</div>
                    <div class="stat product-primary-article">
                        {{ $primaryArticle !== '' ? $primaryArticle : '—' }}
                        @if($product->sku)
                            <span class="product-inline-sku">({{ $product->sku }})</span>
                        @endif
                        @if($catalogSchemePosition !== '')
                            <span class="tag" title="Позиция на схеме">На схеме {{ $catalogSchemePosition }}</span>
                        @endif
                        @if($isTeslaOfficialProduct)
                            <span class="tag product-source-tag" title="tesla.com">tesla.com</span>
                        @endif
                    </div>

                    @if($product->donorCar)
                        <div class="product-donor-summary">
                            @if($donorMainImage)
                                <a class="product-donor-summary__photo" href="{{ route('admin.donor-cars.show', $product->donorCar) }}">
                                    <img src="{{ $imageUrl($donorMainImage) }}" alt="Донор {{ $product->donorCar->vin }}">
                                </a>
                            @endif
                            <div class="product-donor-summary__body">
                                <div class="help">{{ $donorSummaryLabel }}</div>
                                <div class="product-donor-summary__line">
                                    <a class="product-donor-summary__vin" href="{{ route('admin.donor-cars.show', $product->donorCar) }}">{{ $product->donorCar->vin }}</a>
                                </div>
                                <div class="product-stock-placement-list">
                                    @forelse($stockPlacementRows as $placement)
                                        <div class="product-stock-placement">
                                            <span><strong>{{ "\u{0421}\u{043A}\u{043B}\u{0430}\u{0434}" }}:</strong> {{ $placement['warehouse'] }}</span>
                                            @unless($placement['is_donor_warehouse'])
                                                <span><strong>{{ "\u{042D}\u{0442}\u{0430}\u{0436}" }}:</strong> {{ $placement['floor'] }}</span>
                                                <span><strong>{{ "\u{042F}\u{0447}\u{0435}\u{0439}\u{043A}\u{0430}" }}:</strong> {{ $placement['cell'] }}</span>
                                            @endunless
                                            @if($placement['quantity'] !== 1)
                                                <span><strong>{{ "\u{041A}\u{043E}\u{043B}-\u{0432}\u{043E}" }}:</strong> {{ $placement['quantity'] }}</span>
                                            @endif
                                        </div>
                                    @empty
                                        <div class="product-stock-placement product-stock-placement--empty">
                                            {{ "\u{0421}\u{043A}\u{043B}\u{0430}\u{0434}, \u{044D}\u{0442}\u{0430}\u{0436} \u{0438} \u{044F}\u{0447}\u{0435}\u{0439}\u{043A}\u{0430} \u{043D}\u{0435} \u{0443}\u{043A}\u{0430}\u{0437}\u{0430}\u{043D}\u{044B}" }}
                                        </div>
                                    @endforelse
                                </div>
                            </div>
                        </div>
                    @endif

                    @if($vehicleQuantityText !== null)
                        <div class="product-catalog-name-line"><strong>{{ "\u{041A}\u{043E}\u{043B}-\u{0432}\u{043E} \u{043D}\u{0430} \u{043C}\u{0430}\u{0448}\u{0438}\u{043D}\u{0435}" }}:</strong> <span>{{ $vehicleQuantityText }}</span></div>
                    @endif

                    <div class="product-catalog-name-line"><strong>Название RU:</strong> <span>{{ $catalogNameRu['text'] }}</span>
                        @if($catalogItem && ! $isSoldProduct)
                            <form method="POST" action="{{ route('admin.products.catalog-name.update', $product) }}" class="product-catalog-name-form" data-product-catalog-name-form data-current-name="{{ $catalogNameRu['text'] }}" data-name-type-label="RU">
                                @csrf
                                @method('PATCH')
                                <input type="hidden" name="name_type" value="name_ru">
                                <input type="hidden" name="name" value="{{ $catalogNameRu['text'] }}" data-product-catalog-name-input>
                                <button type="button" class="product-catalog-name-edit" title="Редактировать RU название" aria-label="Редактировать RU название" data-product-catalog-name-edit>&#9998;</button>
                            </form>
                        @endif
                        @if($catalogNameRuManual)
                            <span class="tag">Вручную</span>
                        @endif
                        @if(! $catalogNameRuManual && $catalogNameSources['ru']['site'])
                            @if($catalogNameSources['ru']['url'])
                                <a class="tag" href="{{ $catalogNameSources['ru']['url'] }}" target="_blank" rel="noopener">{{ $catalogNameSources['ru']['site'] }}</a>
                            @else
                                <span class="tag">{{ $catalogNameSources['ru']['site'] }}</span>
                            @endif
                        @endif
                    </div>
                    <div class="product-catalog-name-line"><strong>Назва UA:</strong> <span>{{ $catalogNameUa['text'] !== '' ? $catalogNameUa['text'] : '—' }}</span>
                        @if($catalogItem && ! $isSoldProduct)
                            <form method="POST" action="{{ route('admin.products.catalog-name.update', $product) }}" class="product-catalog-name-form" data-product-catalog-name-form data-current-name="{{ $catalogNameUa['text'] }}" data-name-type-label="UA">
                                @csrf
                                @method('PATCH')
                                <input type="hidden" name="name_type" value="name_ua">
                                <input type="hidden" name="name" value="{{ $catalogNameUa['text'] }}" data-product-catalog-name-input>
                                <button type="button" class="product-catalog-name-edit" title="Редактировать UA название" aria-label="Редактировать UA название" data-product-catalog-name-edit>&#9998;</button>
                            </form>
                        @endif
                        @if($catalogNameUaManual)
                            <span class="tag">Вручную</span>
                        @endif
                        @if(! $catalogNameUaManual && $catalogNameSources['ua']['site'])
                            @if($catalogNameSources['ua']['url'])
                                <a class="tag" href="{{ $catalogNameSources['ua']['url'] }}" target="_blank" rel="noopener">{{ $catalogNameSources['ua']['site'] }}</a>
                            @else
                                <span class="tag">{{ $catalogNameSources['ua']['site'] }}</span>
                            @endif
                        @endif
                    </div>
                    <p><strong>Модель:</strong> {{ $product->model ?: '—' }}</p>
                    <p><strong>Категория:</strong> {{ $product->category?->name ?: '—' }}</p>
                    <p><strong>Тип запчасти:</strong> {{ $product->part_origin_label ?: '—' }}</p>
                    <p><strong>Цвет:</strong> {{ $product->color ?: '—' }}</p>
                    <p><strong>Цена:</strong>
                        {{ $product->selling_price !== null ? $product->selling_price.' '.$product->currency : '—' }}
                        @if($product->purchase_price !== null)
                            <span class="help">Закупка: {{ $product->purchase_price }} {{ $product->currency }}</span>
                        @endif
                    </p>
                    <p><strong>Состояние:</strong> {{ $conditionTypeLabels[$product->condition_type] ?? $product->condition_type ?: '—' }}</p>
                    <p><strong>Повреждения:</strong> {{ $product->notes ? \Illuminate\Support\Str::ucfirst($product->notes) : 'Неизвестно' }}</p>
                    <p><strong>Наличие:</strong> {{ $storageStatusLabel ?: '—' }} <span class="help">Остаток: {{ $stockQuantity }} {{ $unitLabels[$product->unit] ?? $product->unit }}</span></p>

                    <div class="product-description-block">
                        <strong>Описание</strong>
                        <div class="long-text">{{ $displayDescription !== '' ? $displayDescription : '—' }}</div>
                    </div>

                    <div class="actions">
                        <a class="btn btn-secondary" href="{{ url('/admin/zapchasti') }}">Назад к запчастям</a>
                    </div>
                </div>

                <aside class="product-photo-manager">
                    <div class="help">Фото товара</div>
                    @if($storedProductImages->isNotEmpty())
                        @if(! $isSoldProduct && $storedProductImages->count() > 1)
                            <form method="POST" action="{{ route('admin.products.photos.order', $product) }}" hidden data-product-photo-order-form>
                                @csrf
                                @method('PATCH')
                            </form>
                        @endif

                        <div class="product-photo-manager__grid" data-product-photo-sortable>
                            @foreach($storedProductImages as $index => $photo)
                                <div class="product-photo-manager__item" data-product-photo-tile data-photo="{{ $photo }}">
                                    <img src="{{ $imageUrl($photo) }}" alt="Фото {{ $product->name }}">
                                    <button type="button" class="product-photo-manager__open" data-product-photo-index="{{ $index }}" aria-label="Открыть фото"></button>
                                    @unless($isSoldProduct)
                                        @if($storedProductImages->count() > 1)
                                            <button type="button" class="product-photo-manager__drag-handle" data-product-photo-drag-handle aria-label="Перетащить фото">
                                                <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                                    <path d="M9 5h2v2H9V5Zm4 0h2v2h-2V5ZM9 9h2v2H9V9Zm4 0h2v2h-2V9Zm-4 4h2v2H9v-2Zm4 0h2v2h-2v-2Zm-4 4h2v2H9v-2Zm4 0h2v2h-2v-2Z" />
                                                </svg>
                                            </button>
                                        @endif
                                        @unless($isTeslaDownloadedImage($photo))
                                            <form method="POST" action="{{ route('admin.products.photos.destroy', $product) }}" class="product-photo-manager__delete-form" data-product-photo-delete-form>
                                                @csrf
                                                @method('DELETE')
                                                <input type="hidden" name="photo" value="{{ $photo }}">
                                                <button type="submit" class="product-photo-manager__delete-button" aria-label="Удалить фото">
                                                    <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                                        <path d="M9 3h6l1 2h4v2H4V5h4l1-2Zm1 6h2v9h-2V9Zm4 0h2v9h-2V9ZM7 9h2v10h6V9h2v12H7V9Z" />
                                                    </svg>
                                                </button>
                                            </form>
                                        @endunless
                                    @endunless
                                    @if($loop->first)
                                        <span class="tag product-photo-manager__main-tag">Главное</span>
                                    @endif
                                    @if($isTeslaDownloadedImage($photo))
                                        <span class="tag product-photo-manager__source-tag">tesla.com</span>
                                    @endif
                                </div>
                            @endforeach
                        </div>
                    @else
                        <div class="empty product-photo-manager__empty">Фото нет.</div>
                    @endif

                    @if($catalogSchemeImages->isNotEmpty())
                        <div class="product-catalog-schemes product-catalog-schemes--aside">
                            <div class="help product-catalog-schemes__title">Схема узла</div>
                            @foreach($catalogSchemeImages as $index => $schemeImage)
                                <button type="button" class="product-catalog-scheme" data-product-scheme-index="{{ $index }}">
                                    <img src="{{ $imageUrl($schemeImage) }}" alt="Схема {{ $catalogSchemeItem?->part_number ?: $primaryArticle }}">
                                </button>
                            @endforeach
                        </div>
                    @endif

                    @if($storedProductImages->isNotEmpty() || $catalogSchemeImages->isNotEmpty())
                        <dialog class="product-photo-lightbox" data-product-photo-lightbox>
                            <button type="button" class="btn btn-secondary product-photo-lightbox__close" data-product-photo-close aria-label="Закрыть">&times;</button>
                            <button type="button" class="btn btn-secondary product-photo-lightbox__rotate product-photo-lightbox__rotate--counterclockwise" data-product-photo-rotate data-product-photo-rotate-degrees="270" aria-label="Повернуть изображение против часовой стрелки">
                                <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                    <path d="M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"/>
                                    <path d="M3 3v5h5"/>
                                </svg>
                            </button>
                            <button type="button" class="btn btn-secondary product-photo-lightbox__rotate product-photo-lightbox__rotate--clockwise" data-product-photo-rotate data-product-photo-rotate-degrees="90" aria-label="Повернуть изображение по часовой стрелке">
                                <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
                                    <path d="M21 12a9 9 0 1 1-9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"/>
                                    <path d="M21 3v5h-5"/>
                                </svg>
                            </button>
                            <button type="button" class="btn btn-secondary product-photo-lightbox__nav product-photo-lightbox__nav--prev" data-product-photo-prev aria-label="Предыдущее изображение">&#8249;</button>
                            <div class="product-photo-lightbox__stage">
                                <img src="" alt="Изображение {{ $product->name }}" data-product-photo-lightbox-image>
                            </div>
                            <button type="button" class="btn btn-secondary product-photo-lightbox__nav product-photo-lightbox__nav--next" data-product-photo-next aria-label="Следующее изображение">&#8250;</button>
                            <div class="product-photo-lightbox__counter" data-product-photo-counter></div>
                        </dialog>
                    @endif

                    @unless($isSoldProduct)
                        <form method="POST" action="{{ route('admin.products.photos.store', $product) }}" enctype="multipart/form-data" class="product-photo-manager__upload" data-product-photo-upload-form>
                            @csrf
                            <input id="product-photos" type="file" name="photos[]" accept="image/*" multiple required data-product-photo-upload-input>
                            <label class="product-photo-manager__dropzone" for="product-photos" data-product-photo-dropzone>
                                <span class="product-photo-manager__dropzone-title">Перетащите фото сюда</span>
                                <span class="product-photo-manager__dropzone-hint">или нажмите, чтобы выбрать файлы</span>
                                <span class="product-photo-manager__dropzone-status" data-product-photo-upload-status>Файлы не выбраны</span>
                            </label>
                            @error('photos')<div class="error">{{ $message }}</div>@enderror
                            @error('photos.*')<div class="error">{{ $message }}</div>@enderror
                            @error('photo')<div class="error">{{ $message }}</div>@enderror
                        </form>
                    @endunless
                </aside>
            </div>
        </div>

        @if($sameDonorProducts->isNotEmpty())
            <section class="panel">
                <h2 class="section-heading">Эта запчасть на других донорах</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Товар</th>
                            <th>Донор</th>
                            <th>Авто</th>
                            <th>Тип</th>
                            <th>Повреждения</th>
                            <th>Статус</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($sameDonorProducts as $sameProduct)
                        <tr>
                            <td>
                                @php
                                    $sameProductArticle = trim((string) ($sameProduct->external_sku ?: $sameProduct->sourcePartCatalogItem?->part_number));
                                @endphp
                                <a href="{{ route('admin.products.show', $sameProduct) }}">
                                    {{ $sameProductArticle !== '' ? $sameProductArticle : '—' }}
                                    @if($sameProduct->sku)
                                        <span class="product-inline-sku">({{ $sameProduct->sku }})</span>
                                    @endif
                                </a>
                            </td>
                            <td>
                                @if($sameProduct->donorCar)
                                    @php
                                        $sameDonorPreview = collect($sameProduct->donorCar->photos ?? [])->first();
                                    @endphp
                                    @if($sameDonorPreview)
                                        <img class="table-preview" src="{{ $imageUrl($sameDonorPreview) }}" alt="Превью {{ $sameProduct->donorCar->vin }}">
                                    @else
                                        <span class="preview-placeholder">нет фото</span>
                                    @endif
                                    <a href="{{ route('admin.donor-cars.show', $sameProduct->donorCar) }}">#{{ $sameProduct->donorCar->id }}</a>
                                    <div class="help">{{ $sameProduct->donorCar->vin }}</div>
                                @else
                                    —
                                @endif
                            </td>
                            <td>
                                @php
                                    $sameProductColor = trim((string) ($sameProduct->donorCar?->color ?: $sameProduct->color));
                                    $sameProductColorHex = $colorSwatchHex($sameProductColor);
                                @endphp
                                <div class="same-donor-car">
                                    @if($sameProductColor !== '' && $sameProductColorHex)
                                        <span
                                            class="same-donor-car__color"
                                            style="background-color: {{ $sameProductColorHex }}"
                                            title="{{ $sameProductColor }}"
                                            aria-label="{{ $sameProductColor }}"
                                        ></span>
                                    @endif
                                    <span>{{ $sameProduct->donorCar ? collect([$sameProduct->donorCar->brand, $sameProduct->donorCar->model, $sameProduct->donorCar->year])->filter()->implode(' · ') : '—' }}</span>
                                </div>
                            </td>
                            <td>{{ $sameProduct->part_origin_label ?: '—' }}</td>
                            <td>{{ $sameProduct->notes ? \Illuminate\Support\Str::ucfirst($sameProduct->notes) : 'Неизвестно' }}</td>
                            <td>{{ $sameProduct->storage_status_label }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </section>
        @endif

        <section class="panel">
            <h2 class="section-heading">Вся информация</h2>
            <div class="detail-grid">
                @foreach($details as $label => $value)
                    <div class="detail-row">
                        <span>{{ $label }}</span>
                        <strong>{{ filled($value) ? $value : '—' }}</strong>
                    </div>
                @endforeach
            </div>
        </section>

        <div class="grid grid-2">
            <section class="panel">
                <h2 class="section-heading">Описание</h2>
                <div class="long-text">{{ $displayDescription !== '' ? $displayDescription : '—' }}</div>
            </section>
            <section class="panel">
                <h2 class="section-heading">Совместимость</h2>
                <div class="long-text">{{ $product->compatibility ?: '—' }}</div>
            </section>
        </div>

        <section class="panel">
            <h2 class="section-heading">Примечания</h2>
            <div class="long-text">{{ $product->notes ?: '—' }}</div>
        </section>

        @if($catalogItem)
            <section class="panel">
                <h2 class="section-heading">Данные из каталога</h2>
                <div class="detail-grid detail-grid-3">
                    <div class="detail-row">
                        <span>Название RU</span>
                        <strong>
                            {{ $catalogNameRu['text'] }}
                            @if($catalogNameRuManual)
                                <span class="tag">Вручную</span>
                            @endif
                            @if(! $catalogNameRuManual && $catalogNameSources['ru']['site'])
                                @if($catalogNameSources['ru']['url'])
                                    <a class="tag" href="{{ $catalogNameSources['ru']['url'] }}" target="_blank" rel="noopener">{{ $catalogNameSources['ru']['site'] }}</a>
                                @else
                                    <span class="tag">{{ $catalogNameSources['ru']['site'] }}</span>
                                @endif
                            @endif
                        </strong>
                    </div>
                    <div class="detail-row">
                        <span>Название UA</span>
                        <strong>
                            {{ $catalogNameUa['text'] !== '' ? $catalogNameUa['text'] : '—' }}
                            @if($catalogNameUaManual)
                                <span class="tag">Вручную</span>
                            @endif
                            @if(! $catalogNameUaManual && $catalogNameSources['ua']['site'])
                                @if($catalogNameSources['ua']['url'])
                                    <a class="tag" href="{{ $catalogNameSources['ua']['url'] }}" target="_blank" rel="noopener">{{ $catalogNameSources['ua']['site'] }}</a>
                                @else
                                    <span class="tag">{{ $catalogNameSources['ua']['site'] }}</span>
                                @endif
                            @endif
                        </strong>
                    </div>
                    <div class="detail-row">
                        <span>Название EN</span>
                        <strong>{{ $catalogNameEn !== '' ? $catalogNameEn : '—' }}</strong>
                    </div>
                    <div class="detail-row"><span>Номер детали</span><strong>{{ $catalogItem->part_number ?: '—' }}</strong></div>
                    <div class="detail-row"><span>Категория</span><strong>{{ collect([$catalogItem->main_category_name, $catalogItem->subcategory_name, $catalogItem->node_name])->filter()->implode(' / ') ?: '—' }}</strong></div>
                    <div class="detail-row"><span>Модель</span><strong>{{ $catalogItem->model_label ?: $catalogItem->model_name ?: '—' }}</strong></div>
                    <div class="detail-row"><span>Годы</span><strong>{{ collect([$catalogItem->year_from, $catalogItem->year_to])->filter()->implode(' - ') ?: '—' }}</strong></div>
                    <div class="detail-row"><span>Качество</span><strong>{{ $catalogItem->quality ?: '—' }}</strong></div>
                    <div class="detail-row"><span>Наличие</span><strong>{{ $catalogItem->availability ?: '—' }}</strong></div>
                </div>
                @if($catalogSourceUrl && ! ($catalogNameRuManual || $catalogNameUaManual))
                    <div style="margin-top:12px;">
                        <a href="{{ $catalogSourceUrl }}" target="_blank" rel="noopener">Открыть источник</a>
                    </div>
                @endif
            </section>
        @endif

        @if($nikolaCarsOfficialEnrichment)
            <section class="panel product-tesla-official-panel">
                <div class="product-tesla-official-heading">
                    <h2 class="section-heading">Данные Tesla.com</h2>
                    <span @class([
                        'tag',
                        'product-tesla-official-match--exact' => $nikolaCarsOfficialEnrichment->matchType() === \App\Services\NikolaCarsOfficialPartMatch::TYPE_EXACT,
                        'product-tesla-official-match--fallback' => $nikolaCarsOfficialEnrichment->matchType() === \App\Services\NikolaCarsOfficialPartMatch::TYPE_SEVEN_DIGIT_PREFIX,
                    ])>{{ $nikolaCarsOfficialMatchLabel }}</span>
                </div>

                <div class="detail-grid detail-grid-3">
                    <div class="detail-row">
                        <span>Запрошенный артикул</span>
                        <strong>{{ $nikolaCarsOfficialEnrichment->requestedPartNumber !== '' ? $nikolaCarsOfficialEnrichment->requestedPartNumber : '—' }}</strong>
                    </div>
                    <div class="detail-row">
                        <span>Артикул Tesla.com</span>
                        <strong>
                            @if($nikolaCarsOfficialEnrichment->officialItem)
                                <a href="{{ route('admin.tesla-official-catalog.show', $nikolaCarsOfficialEnrichment->officialItem) }}">
                                    {{ $nikolaCarsOfficialEnrichment->officialPartNumber ?: 'Открыть' }}
                                </a>
                            @else
                                —
                            @endif
                        </strong>
                    </div>
                    <div class="detail-row">
                        <span>Название Tesla.com</span>
                        <strong>{{ $nikolaCarsOfficialEnrichment->officialName ?: '—' }}</strong>
                    </div>
                    <div class="detail-row">
                        <span>Категория Tesla.com</span>
                        <strong>{{ $nikolaCarsOfficialEnrichment->categoryPath ?: '—' }}</strong>
                    </div>
                    <div class="detail-row">
                        <span>Совместимость</span>
                        <strong>{{ collect($nikolaCarsOfficialEnrichment->compatibilityModels)->implode(', ') ?: '—' }}</strong>
                    </div>
                    <div class="detail-row">
                        <span>Позиция на схеме</span>
                        <strong>{{ $nikolaCarsOfficialEnrichment->schemeNumber !== null ? $nikolaCarsOfficialEnrichment->schemeNumber : '—' }}</strong>
                    </div>
                </div>

                @if($nikolaCarsOfficialEnrichment->occurrences !== [])
                    <table class="product-tesla-official-occurrences">
                        <thead>
                        <tr>
                            <th>Model</th>
                            <th>Category</th>
                            <th>Subcategory</th>
                            <th>Group</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($nikolaCarsOfficialEnrichment->occurrences as $occurrence)
                            <tr>
                                <td>{{ $occurrence['model'] ?: '—' }}</td>
                                <td>{{ $occurrence['category'] ?: '—' }}</td>
                                <td>{{ $occurrence['subcategory'] ?: '—' }}</td>
                                <td>{{ $occurrence['group'] ?: '—' }}</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif

                @if($officialPartImagesForInline->isNotEmpty() || $officialSchemeImagesForInline->isNotEmpty())
                    <div class="product-tesla-official-media">
                        @foreach($officialPartImagesForInline->take(4) as $officialImage)
                            <a href="{{ $imageUrl($officialImage) }}" target="_blank" rel="noopener">
                                <img src="{{ $imageUrl($officialImage) }}" alt="Tesla.com {{ $nikolaCarsOfficialEnrichment->officialPartNumber }}">
                            </a>
                        @endforeach
                        @foreach($officialSchemeImagesForInline->take(2) as $schemeImage)
                            <a href="{{ $imageUrl($schemeImage) }}" target="_blank" rel="noopener">
                                <img src="{{ $imageUrl($schemeImage) }}" alt="Схема Tesla.com {{ $nikolaCarsOfficialEnrichment->officialPartNumber }}">
                            </a>
                        @endforeach
                    </div>
                @endif
            </section>
        @endif

        <section class="panel">
            <h2 class="section-heading">Остатки по ячейкам</h2>
            <table>
                <thead>
                    <tr>
                        <th>Склад</th>
                        <th>Ячейка</th>
                        <th>Кол-во</th>
                        <th>В резерве</th>
                        <th>Доступно</th>
                        <th>Проверка</th>
                        <th>Приемка</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($product->stockItems as $stockItem)
                    <tr>
                        <td>{{ $stockItem->warehouse?->name ?: '—' }}</td>
                        <td>{{ $stockItem->location?->full_code ?: '—' }}</td>
                        <td>{{ $stockItem->quantity }}</td>
                        <td>{{ $stockItem->reserved_quantity }}</td>
                        <td>{{ $stockItem->available_quantity }}</td>
                        <td>{{ $testingLabels[$stockItem->testing_status] ?? $stockItem->testing_status }}</td>
                        <td>{{ optional($stockItem->received_at)->format('Y-m-d H:i') ?: '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="7" class="empty">Остатков пока нет.</td></tr>
                @endforelse
                </tbody>
            </table>
        </section>

        <section class="panel">
            <h2 class="section-heading">Закупки</h2>
            <table>
                <thead>
                    <tr>
                        <th>Дата</th>
                        <th>Документ</th>
                        <th>Поставщик</th>
                        <th>Склад / ячейка</th>
                        <th>Кол-во</th>
                        <th>Закупка</th>
                        <th>Продажа</th>
                        <th>Комментарий</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($product->purchaseItems->sortByDesc(fn ($item) => $item->purchase?->purchase_date ?? $item->created_at) as $item)
                    <tr>
                        <td>{{ optional($item->purchase?->purchase_date)->format('Y-m-d') ?: '—' }}</td>
                        <td>{{ $item->purchase?->document_number ?: '—' }}</td>
                        <td>{{ $item->purchase?->counterparty?->name ?: '—' }}</td>
                        <td>{{ collect([$item->warehouse?->name, $item->location?->full_code])->filter()->implode(' / ') ?: '—' }}</td>
                        <td>{{ $item->quantity }}</td>
                        <td>{{ $item->purchase_price }} {{ $item->currency }}</td>
                        <td>{{ $item->selling_price }} {{ $item->currency }}</td>
                        <td>{{ $item->comment ?: '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="8" class="empty">Закупок по товару пока нет.</td></tr>
                @endforelse
                </tbody>
            </table>
        </section>

        <section class="panel">
            <h2 class="section-heading">Последние движения</h2>
            <table>
                <thead>
                    <tr>
                        <th>Тип</th>
                        <th>Кол-во</th>
                        <th>Откуда</th>
                        <th>Куда</th>
                        <th>Контрагент</th>
                        <th>Документ</th>
                        <th>Комментарий</th>
                        <th>Дата</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($product->movements->sortByDesc('created_at') as $movement)
                    <tr>
                        <td>{{ $movementLabels[$movement->type] ?? $movement->type }}</td>
                        <td>{{ $movement->quantity }}</td>
                        <td>{{ $movement->fromLocation?->full_code ?: '—' }}</td>
                        <td>{{ $movement->toLocation?->full_code ?: '—' }}</td>
                        <td>{{ $movement->counterparty?->name ?: '—' }}</td>
                        <td>{{ $movement->document_number ?: '—' }}</td>
                        <td>{{ $movement->comment ?: $movement->reason ?: '—' }}</td>
                        <td>{{ optional($movement->created_at)->format('Y-m-d H:i') }}</td>
                    </tr>
                @empty
                    <tr><td colspan="8" class="empty">Движений пока нет.</td></tr>
                @endforelse
                </tbody>
            </table>
        </section>

        <section class="panel">
            <h2 class="section-heading">Использование в заказ-нарядах</h2>
            <table>
                <thead>
                    <tr>
                        <th>Заказ</th>
                        <th>Статус</th>
                        <th>Авто</th>
                        <th>Кол-во</th>
                        <th>Цена</th>
                        <th>Сумма</th>
                        <th>Примечание</th>
                    </tr>
                </thead>
                <tbody>
                @forelse($product->stoWorkOrderParts->sortByDesc('created_at') as $part)
                    <tr>
                        <td>
                            @if($part->order)
                                <a href="{{ route('admin.sto-work-orders.show', $part->order) }}">{{ $part->order->number }}</a>
                            @else
                                —
                            @endif
                        </td>
                        <td>{{ $part->order?->status_label ?: '—' }}</td>
                        <td>{{ $part->order?->car_title ?: '—' }}</td>
                        <td>{{ $part->quantity }}</td>
                        <td>{{ $part->unit_price_uah }} грн</td>
                        <td>{{ $part->total_price_uah }} грн</td>
                        <td>{{ $part->note ?: '—' }}</td>
                    </tr>
                @empty
                    <tr><td colspan="7" class="empty">В заказ-нарядах товар пока не использовался.</td></tr>
                @endforelse
                </tbody>
            </table>
        </section>
    </div>

    <style>
        .page-heading-row { display: flex; align-items: center; gap: 8px; }
        .page-heading-row h1 { min-width: 0; overflow-wrap: anywhere; }
        .page-heading-row .auto-generated-badge { flex: 0 0 auto; margin-left: 0; }
        .product-heading-status { flex: 0 0 auto; }
        .product-heading-status--checked { background: #dcfce7; color: #166534; }
        .product-show { display: grid; gap: 18px; }
        .product-item-main-panel { position: relative; }
        .product-edit-button { position: absolute; top: 14px; right: 14px; padding: 4px 8px; font-size: 12px; line-height: 1.2; }
        .product-item-layout { display: grid; grid-template-columns: minmax(0, 1fr) minmax(260px, 340px); gap: 22px; align-items: start; }
        .product-item-details { min-width: 0; }
        .product-item-details p { overflow-wrap: anywhere; }
        .product-primary-article { font-size: 24px; overflow-wrap: anywhere; }
        .product-inline-sku { color: var(--muted); font-size: .72em; font-weight: 400; white-space: nowrap; }
        .product-source-tag { background: #111827; color: #fff; vertical-align: middle; }
        .product-catalog-name-line { display: flex; align-items: center; gap: 6px; flex-wrap: wrap; margin: 1em 0; overflow-wrap: anywhere; }
        .product-catalog-name-line strong,
        .product-catalog-name-line span { min-width: 0; }
        .auto-generated-badge { display: inline-flex; align-items: center; justify-content: center; width: 20px; min-width: 20px; height: 20px; padding: 0; border: 1px solid #bae6fd; border-radius: 999px; background: #e0f2fe; color: #075985; font-size: 11px; font-weight: 700; line-height: 1; vertical-align: middle; }
        .product-catalog-name-form { display: inline-flex; margin-left: 4px; vertical-align: middle; }
        .product-catalog-name-edit { width: 22px; height: 22px; padding: 0; border: 0; border-radius: 999px; background: transparent; color: var(--accent); font-size: 14px; line-height: 1; }
        .product-catalog-name-edit:hover,
        .product-catalog-name-edit:focus { background: var(--accent-soft); outline: none; }
        .product-donor-summary { display: flex; align-items: center; gap: 12px; margin: 12px 0 16px; padding: 10px 0; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line); }
        .product-donor-summary__photo { flex: 0 0 auto; display: block; width: 86px; overflow: hidden; border-radius: 8px; }
        .product-donor-summary__photo img { display: block; width: 100%; aspect-ratio: 4 / 3; object-fit: cover; border: 1px solid var(--line); border-radius: 8px; background: #fff; }
        .product-donor-summary__body { min-width: 0; }
        .product-donor-summary__line { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; min-width: 0; }
        .product-donor-summary__vin { display: inline-block; max-width: 100%; font-size: 16px; font-weight: 800; overflow-wrap: anywhere; }
        .product-donor-summary__tag { flex: 0 0 auto; }
        .product-stock-placement-list { display: grid; gap: 4px; margin-top: 6px; }
        .product-stock-placement { display: flex; flex-wrap: wrap; gap: 4px 10px; color: var(--muted); font-size: 13px; overflow-wrap: anywhere; }
        .product-stock-placement strong { color: var(--text); }
        .product-stock-placement--empty { color: var(--muted); }
        .product-description-block { display: grid; gap: 8px; margin: 16px 0; }
        .product-photo-manager { display: grid; gap: 10px; padding-top: 28px; }
        .product-photo-manager__grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }
        .product-photo-manager__item { position: relative; display: block; width: 100%; aspect-ratio: 4 / 3; border-radius: 8px; background: #fff; color: var(--text); overflow: hidden; touch-action: none; }
        .product-photo-manager__item.is-dragging { opacity: .32; outline: 2px dashed var(--accent); outline-offset: -2px; background: var(--accent-soft); }
        .product-photo-manager__item.is-dragging img { opacity: .45; }
        .product-photo-manager__item.is-drop-target img { border-color: var(--accent); box-shadow: 0 0 0 3px rgba(15, 118, 110, .18); }
        .product-photo-manager__item img { display: block; width: 100%; height: 100%; object-fit: contain; border: 1px solid var(--line); border-radius: 8px; background: #fff; }
        .product-photo-manager__open { position: absolute; inset: 0; z-index: 1; width: 100%; height: 100%; padding: 0; border: 0; border-radius: 8px; background: transparent; color: transparent; cursor: zoom-in; }
        .product-photo-manager__open:hover,
        .product-photo-manager__open:focus-visible { background: rgba(15, 118, 110, .08); outline: 2px solid rgba(15, 118, 110, .28); outline-offset: -2px; }
        .product-photo-manager__drag-handle,
        .product-photo-manager__delete-button { position: absolute; top: 8px; z-index: 3; width: 34px; min-width: 34px; height: 34px; min-height: 34px; padding: 0; border: 1px solid rgba(255, 255, 255, .72); border-radius: 999px; color: #fff; box-shadow: 0 8px 18px rgba(29, 42, 49, .22); }
        .product-photo-manager__drag-handle { left: 8px; background: rgba(29, 42, 49, .86); cursor: grab; }
        .product-photo-manager__drag-handle:active { cursor: grabbing; }
        .product-photo-manager__delete-form { position: absolute; top: 8px; right: 8px; z-index: 4; margin: 0; }
        .product-photo-manager__delete-button { position: static; background: rgba(159, 45, 45, .96); }
        .product-photo-manager__drag-handle svg,
        .product-photo-manager__delete-button svg { display: block; width: 20px; height: 20px; fill: currentColor; }
        .product-photo-manager__item .tag { position: absolute; bottom: 8px; z-index: 2; box-shadow: 0 6px 16px rgba(25, 32, 36, .12); }
        .product-photo-manager__main-tag { left: 8px; }
        .product-photo-manager__source-tag { right: 8px; background: #111827; color: #fff; }
        .product-photo-manager__drag-preview { position: fixed; left: 0; top: 0; z-index: 80; pointer-events: none; overflow: hidden; contain: layout paint; will-change: transform; border: 2px solid var(--accent); border-radius: 8px; background: #fff; box-shadow: 0 18px 42px rgba(29, 42, 49, .34); opacity: .96; transform-origin: top left; transition: none; }
        .product-photo-manager__drag-preview img { display: block; width: 100%; height: 100%; object-fit: contain; }
        .product-photo-lightbox { width: min(1120px, calc(100vw - 32px)); height: min(820px, calc(100vh - 32px)); max-height: calc(100vh - 32px); padding: 48px 62px 44px; border: 1px solid var(--line); border-radius: 18px; background: rgba(255, 255, 255, .98); box-shadow: 0 24px 70px rgba(25, 32, 36, .25); box-sizing: border-box; }
        .product-photo-lightbox::backdrop { background: rgba(29, 42, 49, .6); }
        .product-photo-lightbox__stage { display: grid; place-items: center; width: 100%; height: 100%; min-width: 0; min-height: 0; overflow: hidden; border-radius: 8px; background: #fff; }
        .product-photo-lightbox img { display: block; width: 100%; height: 100%; min-width: 0; min-height: 0; object-fit: contain; border-radius: 8px; background: #fff; }
        .product-photo-lightbox__close { position: absolute; top: 12px; right: 12px; width: 34px; height: 34px; padding: 0; font-size: 22px; line-height: 1; }
        .product-photo-lightbox__rotate { position: absolute; top: 12px; width: 34px; height: 34px; padding: 0; }
        .product-photo-lightbox__rotate--clockwise { right: 54px; }
        .product-photo-lightbox__rotate--counterclockwise { right: 96px; }
        .product-photo-lightbox__rotate svg { display: block; width: 19px; height: 19px; margin: auto; fill: none; stroke: currentColor; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; }
        .product-photo-lightbox__nav { position: absolute; top: 50%; width: 38px; height: 56px; padding: 0; transform: translateY(-50%); font-size: 34px; line-height: 1; }
        .product-photo-lightbox__nav--prev { left: 12px; }
        .product-photo-lightbox__nav--next { right: 12px; }
        .product-photo-lightbox__counter { position: absolute; left: 50%; bottom: 14px; transform: translateX(-50%); color: var(--muted); font-size: 13px; font-weight: 700; }
        .product-photo-manager__upload { display: grid; gap: 8px; padding-top: 8px; border-top: 1px solid var(--line); }
        .product-photo-manager__upload input[type="file"] { position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0 0 0 0); white-space: nowrap; clip-path: inset(50%); }
        .product-photo-manager__dropzone { display: grid; align-content: center; gap: 6px; min-height: 126px; margin: 0; padding: 16px; border: 1px dashed var(--line); border-radius: 8px; background: #fbfcfc; color: var(--text); cursor: pointer; text-align: center; transition: border-color .16s ease, background-color .16s ease, color .16s ease; }
        .product-photo-manager__dropzone:hover,
        .product-photo-manager__dropzone.is-dragover { border-color: var(--accent); background: var(--accent-soft); color: var(--accent); }
        .product-photo-manager__dropzone-title { font-weight: 800; line-height: 1.25; }
        .product-photo-manager__dropzone-hint,
        .product-photo-manager__dropzone-status { color: var(--muted); font-size: 13px; line-height: 1.35; }
        .product-photo-manager__dropzone-status { font-weight: 700; }
        .product-photo-manager__empty { padding: 14px; border: 1px dashed var(--line); border-radius: 8px; }
        .product-tesla-official-heading { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 14px; }
        .product-tesla-official-heading .section-heading { margin: 0; }
        .product-tesla-official-match--exact { background: #dcfce7; border-color: #bbf7d0; color: #166534; }
        .product-tesla-official-match--fallback { background: #fef3c7; border-color: #fde68a; color: #92400e; }
        .product-tesla-official-occurrences { margin-top: 16px; }
        .product-tesla-official-media { display: grid; grid-template-columns: repeat(auto-fill, minmax(140px, 1fr)); gap: 10px; margin-top: 16px; }
        .product-tesla-official-media a { display: block; min-width: 0; border: 1px solid var(--line); border-radius: 8px; background: #fff; overflow: hidden; }
        .product-tesla-official-media img { display: block; width: 100%; aspect-ratio: 4 / 3; object-fit: contain; background: #fff; }
        .product-catalog-schemes { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px; margin-top: 14px; }
        .product-catalog-schemes--aside { grid-template-columns: 1fr; }
        .product-catalog-schemes__title { margin-bottom: -4px; }
        .product-catalog-scheme { display: block; width: 100%; padding: 0; border: 1px solid var(--line); border-radius: 8px; background: #fff; overflow: hidden; cursor: zoom-in; }
        .product-catalog-schemes img { display: block; width: 100%; max-height: 360px; object-fit: contain; background: #fff; }
        .section-heading { margin: 0 0 14px; font-size: 20px; line-height: 1.25; }
        .detail-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px 14px; }
        .detail-grid-3 { grid-template-columns: repeat(3, minmax(0, 1fr)); }
        .detail-row { display: grid; gap: 3px; min-width: 0; padding-bottom: 10px; border-bottom: 1px solid var(--line); }
        .detail-row span { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .06em; }
        .detail-row strong { font-size: 14px; overflow-wrap: anywhere; }
        .long-text { white-space: pre-wrap; line-height: 1.55; overflow-wrap: anywhere; }
        .same-donor-car { display: inline-flex; align-items: center; gap: 8px; min-width: 0; }
        .same-donor-car__color { flex: 0 0 auto; width: 14px; height: 14px; border: 1px solid rgba(17, 24, 39, .22); border-radius: 999px; box-shadow: inset 0 0 0 1px rgba(255, 255, 255, .62); }
        @media (max-width: 980px) {
            .product-item-layout { grid-template-columns: 1fr; }
            .product-photo-manager { padding-top: 0; }
            .detail-grid,
            .detail-grid-3 { grid-template-columns: 1fr; }
        }
    </style>

    <script>
        (() => {
            let productPhotoPaths = @json($storedProductImages->values());
            let photos = @json($storedProductImages->map(fn ($photo) => $imageUrl($photo))->values());
            const rotatePhotoUrl = @json(route('admin.products.photos.rotate', $product));
            const csrfToken = @json(csrf_token());
            const schemes = @json($catalogSchemeImages->map(fn ($schemeImage) => $imageUrl($schemeImage))->values());
            let lightboxImages = [...photos, ...schemes];
            const lightbox = document.querySelector('[data-product-photo-lightbox]');
            const image = lightbox?.querySelector('[data-product-photo-lightbox-image]');
            const counter = lightbox?.querySelector('[data-product-photo-counter]');
            const closeButton = lightbox?.querySelector('[data-product-photo-close]');
            const rotateButtons = Array.from(lightbox?.querySelectorAll('[data-product-photo-rotate]') || []);
            const prevButton = lightbox?.querySelector('[data-product-photo-prev]');
            const nextButton = lightbox?.querySelector('[data-product-photo-next]');
            const uploadForm = document.querySelector('[data-product-photo-upload-form]');
            const uploadInput = document.querySelector('[data-product-photo-upload-input]');
            const uploadDropzone = document.querySelector('[data-product-photo-dropzone]');
            const uploadStatus = document.querySelector('[data-product-photo-upload-status]');
            let currentIndex = 0;

            const setUploadStatus = (message) => {
                if (uploadStatus) {
                    uploadStatus.textContent = message;
                }
            };

            const submitPhotoUpload = (files) => {
                if (!uploadInput || !uploadForm) {
                    return;
                }

                const imageFiles = Array.from(files || []).filter((file) => file.type.startsWith('image/'));

                if (imageFiles.length === 0) {
                    uploadInput.value = '';
                    setUploadStatus('Файлы не выбраны');
                    alert('Выберите фото в формате изображения.');
                    return;
                }

                if (imageFiles.length > 20) {
                    uploadInput.value = '';
                    setUploadStatus('Файлы не выбраны');
                    alert('За один раз можно добавить до 20 фото.');
                    return;
                }

                const transfer = new DataTransfer();
                imageFiles.forEach((file) => transfer.items.add(file));
                uploadInput.files = transfer.files;
                setUploadStatus(`Выбрано файлов: ${imageFiles.length}. Загрузка...`);
                uploadForm.submit();
            };

            uploadInput?.addEventListener('change', () => submitPhotoUpload(uploadInput.files));
            uploadDropzone?.addEventListener('dragenter', (event) => {
                event.preventDefault();
                uploadDropzone.classList.add('is-dragover');
            });
            uploadDropzone?.addEventListener('dragover', (event) => {
                event.preventDefault();
                uploadDropzone.classList.add('is-dragover');
            });
            uploadDropzone?.addEventListener('dragleave', (event) => {
                if (!uploadDropzone.contains(event.relatedTarget)) {
                    uploadDropzone.classList.remove('is-dragover');
                }
            });
            uploadDropzone?.addEventListener('drop', (event) => {
                event.preventDefault();
                uploadDropzone.classList.remove('is-dragover');
                submitPhotoUpload(event.dataTransfer?.files || []);
            });

            const syncLightboxPhotoOrder = () => {
                const sortable = document.querySelector('[data-product-photo-sortable]');
                if (!sortable) {
                    return;
                }

                const tiles = Array.from(sortable.querySelectorAll('[data-product-photo-tile]'));
                productPhotoPaths = tiles
                    .map((tile) => tile.dataset.photo || '')
                    .filter(Boolean);
                photos = tiles
                    .map((tile) => tile.querySelector('img')?.currentSrc || tile.querySelector('img')?.src || '')
                    .filter(Boolean);
                lightboxImages = [...photos, ...schemes];
            };

            const showPhoto = (index) => {
                if (!image || !counter || lightboxImages.length === 0) {
                    return;
                }

                currentIndex = (index + lightboxImages.length) % lightboxImages.length;
                image.src = lightboxImages[currentIndex];
                counter.textContent = `${currentIndex + 1} / ${lightboxImages.length}`;

                const hasMultipleImages = lightboxImages.length > 1;
                if (prevButton) prevButton.hidden = !hasMultipleImages;
                if (nextButton) nextButton.hidden = !hasMultipleImages;
                rotateButtons.forEach((button) => {
                    button.hidden = currentIndex >= productPhotoPaths.length;
                });
            };

            document.querySelectorAll('[data-product-photo-index]').forEach((button) => {
                button.addEventListener('click', () => {
                    showPhoto(Number(button.dataset.productPhotoIndex || 0));
                    lightbox?.showModal();
                });
            });

            document.querySelectorAll('[data-product-scheme-index]').forEach((button) => {
                button.addEventListener('click', () => {
                    showPhoto(photos.length + Number(button.dataset.productSchemeIndex || 0));
                    lightbox?.showModal();
                });
            });

            const sortable = document.querySelector('[data-product-photo-sortable]');
            const orderForm = document.querySelector('[data-product-photo-order-form]');
            const photoOrder = () => Array.from(sortable?.querySelectorAll('[data-product-photo-tile]') || [])
                .map((tile) => tile.dataset.photo || '')
                .filter(Boolean);
            const mainPhotoLabel = '\u0413\u043b\u0430\u0432\u043d\u043e\u0435';

            if (sortable && orderForm) {
                let draggedTile = null;
                let dragPreview = null;
                let dropTarget = null;
                let dragOffsetX = 0;
                let dragOffsetY = 0;
                let pendingDragPoint = null;
                let moveFrame = null;
                let startOrder = [];

                const clearDropTarget = () => {
                    dropTarget?.classList.remove('is-drop-target');
                    dropTarget = null;
                };

                const findDropTarget = (point) => {
                    const targetTile = document.elementFromPoint(point.clientX, point.clientY)?.closest('[data-product-photo-tile]');

                    if (targetTile && targetTile !== draggedTile && sortable.contains(targetTile)) {
                        return targetTile;
                    }

                    const sortableRect = sortable.getBoundingClientRect();
                    const edgeSlack = 42;
                    const isNearSortable = point.clientX >= sortableRect.left - edgeSlack
                        && point.clientX <= sortableRect.right + edgeSlack
                        && point.clientY >= sortableRect.top - edgeSlack
                        && point.clientY <= sortableRect.bottom + edgeSlack;

                    if (! isNearSortable) {
                        return null;
                    }

                    return Array.from(sortable.querySelectorAll('[data-product-photo-tile]'))
                        .filter((tile) => tile !== draggedTile)
                        .map((tile) => {
                            const rect = tile.getBoundingClientRect();
                            const centerX = rect.left + rect.width / 2;
                            const centerY = rect.top + rect.height / 2;

                            return {
                                tile,
                                distance: Math.hypot(point.clientX - centerX, point.clientY - centerY),
                            };
                        })
                        .sort((a, b) => a.distance - b.distance)[0]?.tile || null;
                };

                const moveDragPreview = (clientX, clientY) => {
                    if (! dragPreview) {
                        return;
                    }

                    const x = Math.round(clientX - dragOffsetX);
                    const y = Math.round(clientY - dragOffsetY);
                    dragPreview.style.transform = `translate3d(${x}px, ${y}px, 0) scale(1.04)`;
                };

                const removeDragPreview = () => {
                    dragPreview?.remove();
                    dragPreview = null;
                };

                const createDragPreview = (tile, event) => {
                    const rect = tile.getBoundingClientRect();
                    dragOffsetX = event.clientX - rect.left;
                    dragOffsetY = event.clientY - rect.top;
                    dragPreview = tile.cloneNode(true);
                    dragPreview.classList.remove('is-dragging', 'is-drop-target');
                    dragPreview.classList.add('product-photo-manager__drag-preview');
                    dragPreview.setAttribute('aria-hidden', 'true');
                    dragPreview.removeAttribute('data-product-photo-tile');
                    dragPreview.removeAttribute('data-photo');
                    dragPreview.querySelectorAll('[data-product-photo-index], [data-product-photo-drag-handle], [data-product-photo-delete-form]').forEach((element) => element.remove());
                    dragPreview.style.width = `${rect.width}px`;
                    dragPreview.style.height = `${rect.height}px`;
                    document.body.appendChild(dragPreview);
                    moveDragPreview(event.clientX, event.clientY);
                };

                const updateMainPhotoBadge = () => {
                    sortable.querySelectorAll('.product-photo-manager__item > .tag:not(.product-photo-manager__source-tag)').forEach((badge) => badge.remove());

                    const firstTile = sortable.querySelector('[data-product-photo-tile]');
                    if (! firstTile) {
                        return;
                    }

                    const badge = document.createElement('span');
                    badge.className = 'tag product-photo-manager__main-tag';
                    badge.textContent = mainPhotoLabel;
                    firstTile.appendChild(badge);
                };

                const submitPhotoOrder = async (photos) => {
                    orderForm.querySelectorAll('[data-product-photo-order-input]').forEach((input) => input.remove());
                    photos.forEach((photo) => {
                        const input = document.createElement('input');
                        input.type = 'hidden';
                        input.name = 'photos[]';
                        input.value = photo;
                        input.dataset.productPhotoOrderInput = '1';
                        orderForm.appendChild(input);
                    });

                    try {
                        const response = await fetch(orderForm.action, {
                            method: orderForm.method || 'POST',
                            body: new FormData(orderForm),
                            credentials: 'same-origin',
                            headers: {
                                'Accept': 'application/json',
                                'X-Requested-With': 'XMLHttpRequest',
                            },
                        });

                        if (! response.ok) {
                            throw new Error(`Photo order save failed: ${response.status}`);
                        }

                        syncLightboxPhotoOrder();
                    } catch (error) {
                        window.location.reload();
                    }
                };

                const applyDragMove = (point) => {
                    if (! draggedTile) {
                        return;
                    }

                    moveDragPreview(point.clientX, point.clientY);
                    const targetTile = findDropTarget(point);
                    if (! targetTile) {
                        clearDropTarget();
                        return;
                    }

                    if (dropTarget !== targetTile) {
                        clearDropTarget();
                        dropTarget = targetTile;
                        dropTarget.classList.add('is-drop-target');
                    }
                };

                const applyDrop = (point) => {
                    const targetTile = findDropTarget(point);
                    if (! targetTile || ! draggedTile) {
                        return;
                    }

                    const tiles = Array.from(sortable.querySelectorAll('[data-product-photo-tile]'));
                    const draggedIndex = tiles.indexOf(draggedTile);
                    const targetIndex = tiles.indexOf(targetTile);

                    if (draggedIndex < 0 || targetIndex < 0 || draggedIndex === targetIndex) {
                        return;
                    }

                    sortable.insertBefore(draggedTile, draggedIndex < targetIndex ? targetTile.nextSibling : targetTile);
                };

                const queueDragMove = (event) => {
                    pendingDragPoint = {
                        clientX: event.clientX,
                        clientY: event.clientY,
                    };
                    if (moveFrame !== null) {
                        return;
                    }

                    moveFrame = window.requestAnimationFrame(() => {
                        const pointToApply = pendingDragPoint;
                        pendingDragPoint = null;
                        moveFrame = null;

                        if (pointToApply) {
                            applyDragMove(pointToApply);
                        }
                    });
                };

                const flushDragMove = () => {
                    if (moveFrame !== null) {
                        window.cancelAnimationFrame(moveFrame);
                        moveFrame = null;
                    }

                    const pointToApply = pendingDragPoint;
                    pendingDragPoint = null;

                    if (pointToApply) {
                        applyDragMove(pointToApply);
                    }
                };

                const finishDrag = (handle, event) => {
                    if (! draggedTile) {
                        return;
                    }

                    flushDragMove();
                    applyDrop({
                        clientX: event.clientX,
                        clientY: event.clientY,
                    });
                    draggedTile.classList.remove('is-dragging');
                    draggedTile.style.pointerEvents = '';
                    sortable.classList.remove('is-sorting');
                    clearDropTarget();
                    removeDragPreview();

                    if (handle?.hasPointerCapture?.(event.pointerId)) {
                        handle.releasePointerCapture(event.pointerId);
                    }

                    const nextOrder = photoOrder();
                    const hasChanged = startOrder.join('\n') !== nextOrder.join('\n');
                    draggedTile = null;
                    startOrder = [];

                    if (! hasChanged) {
                        return;
                    }

                    updateMainPhotoBadge();
                    submitPhotoOrder(nextOrder);
                };

                sortable.querySelectorAll('[data-product-photo-drag-handle]').forEach((handle) => {
                    handle.addEventListener('pointerdown', (event) => {
                        if (event.button && event.button !== 0) {
                            return;
                        }

                        draggedTile = handle.closest('[data-product-photo-tile]');
                        if (! draggedTile) {
                            return;
                        }

                        event.preventDefault();
                        startOrder = photoOrder();
                        draggedTile.classList.add('is-dragging');
                        draggedTile.style.pointerEvents = 'none';
                        sortable.classList.add('is-sorting');
                        createDragPreview(draggedTile, event);
                        handle.setPointerCapture?.(event.pointerId);
                    });

                    handle.addEventListener('pointermove', (event) => {
                        if (! draggedTile) {
                            return;
                        }

                        event.preventDefault();
                        queueDragMove(event);
                    });

                    handle.addEventListener('pointerup', (event) => finishDrag(handle, event));
                    handle.addEventListener('pointercancel', (event) => finishDrag(handle, event));
                });
            }

            document.querySelectorAll('[data-product-photo-delete-form]').forEach((form) => {
                form.addEventListener('submit', (event) => {
                    if (! window.confirm('\u0423\u0434\u0430\u043b\u0438\u0442\u044c \u044d\u0442\u043e \u0444\u043e\u0442\u043e?')) {
                        event.preventDefault();
                    }
                });
            });

            document.querySelectorAll('[data-product-catalog-name-edit]').forEach((button) => {
                button.addEventListener('click', () => {
                    const form = button.closest('[data-product-catalog-name-form]');
                    const input = form?.querySelector('[data-product-catalog-name-input]');
                    const currentName = form?.dataset.currentName || input?.value || '';
                    const nameTypeLabel = form?.dataset.nameTypeLabel || '';

                    if (!form || !input) {
                        return;
                    }

                    const nextName = prompt(`Новое ${nameTypeLabel ? nameTypeLabel + ' ' : ''}название запчасти`, currentName);

                    if (nextName === null) {
                        return;
                    }

                    const trimmedName = nextName.trim();

                    if (trimmedName === '') {
                        alert('Название не может быть пустым.');
                        return;
                    }

                    if (trimmedName === currentName.trim()) {
                        return;
                    }

                    input.value = trimmedName;
                    form.submit();
                });
            });

            closeButton?.addEventListener('click', () => lightbox?.close());
            rotateButtons.forEach((rotateButton) => {
                rotateButton.addEventListener('click', async () => {
                    const photoPath = productPhotoPaths[currentIndex] || '';
                    const degrees = Number(rotateButton.dataset.productPhotoRotateDegrees || 90);

                    if (!image || !photoPath) {
                        return;
                    }

                    rotateButtons.forEach((button) => {
                        button.disabled = true;
                    });

                    try {
                        const response = await fetch(rotatePhotoUrl, {
                            method: 'PATCH',
                            headers: {
                                'Accept': 'application/json',
                                'Content-Type': 'application/json',
                                'X-CSRF-TOKEN': csrfToken,
                            },
                            body: JSON.stringify({ photo: photoPath, degrees }),
                        });
                        const payload = await response.json().catch(() => ({}));

                        if (!response.ok) {
                            const message = payload?.message || payload?.errors?.photo?.[0] || 'Не удалось повернуть фото.';
                            throw new Error(message);
                        }

                        const baseUpdatedUrl = payload.url || image.src;
                        const updatedUrl = `${baseUpdatedUrl}${baseUpdatedUrl.includes('?') ? '&' : '?'}rotated_at=${Date.now()}`;
                        photos[currentIndex] = updatedUrl;
                        lightboxImages[currentIndex] = updatedUrl;
                        image.src = updatedUrl;

                        const tiles = Array.from(document.querySelectorAll('[data-product-photo-tile]'));
                        const tileImage = tiles[currentIndex]?.dataset.photo === photoPath
                            ? tiles[currentIndex]?.querySelector('img')
                            : tiles.find((tile) => tile.dataset.photo === photoPath)?.querySelector('img');

                        if (tileImage) {
                            tileImage.src = updatedUrl;
                        }
                    } catch (error) {
                        alert(error?.message || 'Не удалось повернуть фото.');
                    } finally {
                        rotateButtons.forEach((button) => {
                            button.disabled = false;
                        });
                    }
                });
            });
            prevButton?.addEventListener('click', () => showPhoto(currentIndex - 1));
            nextButton?.addEventListener('click', () => showPhoto(currentIndex + 1));

            lightbox?.addEventListener('click', (event) => {
                if (event.target === lightbox) {
                    lightbox.close();
                }
            });

            document.addEventListener('keydown', (event) => {
                if (!lightbox?.open) {
                    return;
                }

                if (event.key === 'ArrowLeft') {
                    showPhoto(currentIndex - 1);
                }

                if (event.key === 'ArrowRight') {
                    showPhoto(currentIndex + 1);
                }
            });
        })();
    </script>
@endsection
